/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectofnaf_carmencastillo;

import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.TimerTask;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.Timer;

/**
 *
 * @author casti
 */
public class Main extends javax.swing.JFrame implements Runnable {

    private ArrayList<Usuario> usuarios;
    private int mouseX, mouseY;
    private int banderaPuertaIz = 0;
    private int banderaPuertaDer = 0;
    private int banderaLuzDer = 0;
    private int banderaLuzIz = 0;
    private int banderaCamara = 0;
    //1 camara cerrada / 0 camara abierta
    public String locationCamara = "stage";

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();

        this.setLocationRelativeTo(null);
        this.setResizable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vMenuJuego = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        JLbtnContinuarNoche = new javax.swing.JLabel();
        JLbtnNuevaPartida = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        vCrearUsuario = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        userLabel3 = new javax.swing.JLabel();
        Jtxtf_UsuarioAdd = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        userLabel4 = new javax.swing.JLabel();
        vMenuJuegoAdmin = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        JLbtnNochePers1 = new javax.swing.JLabel();
        btnContinuarNocheAdmin = new javax.swing.JLabel();
        JLbtnNuevaPartidaAdmin = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        vOficina = new javax.swing.JFrame();
        oficina = new javax.swing.JPanel();
        lbHora = new javax.swing.JLabel();
        btn_luzder = new javax.swing.JLabel();
        ventanader = new javax.swing.JLabel();
        ventanaizq = new javax.swing.JLabel();
        btn_luzizq = new javax.swing.JLabel();
        btn_puertader = new javax.swing.JLabel();
        btn_puertaizq = new javax.swing.JLabel();
        btn_opencam = new javax.swing.JLabel();
        puertizq = new javax.swing.JLabel();
        puertaLuzizq = new javax.swing.JLabel();
        puertder = new javax.swing.JLabel();
        puertaLuzder = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cam = new javax.swing.JPanel();
        monitor = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        camCerrar = new javax.swing.JPanel();
        monitor1 = new javax.swing.JLabel();
        fondo1 = new javax.swing.JLabel();
        povcam = new javax.swing.JPanel();
        lbHoraCam = new javax.swing.JLabel();
        btn_Cam1A = new javax.swing.JLabel();
        btn_Cam1B = new javax.swing.JLabel();
        btn_Cam1C = new javax.swing.JLabel();
        btn_Cam2A = new javax.swing.JLabel();
        btn_Cam2B = new javax.swing.JLabel();
        btn_Cam3 = new javax.swing.JLabel();
        btn_Cam4A = new javax.swing.JLabel();
        btn_Cam4B = new javax.swing.JLabel();
        btn_Cam5 = new javax.swing.JLabel();
        btn_Cam6 = new javax.swing.JLabel();
        btn_Cam7 = new javax.swing.JLabel();
        btn_closecam = new javax.swing.JLabel();
        lbMapa = new javax.swing.JLabel();
        setearCamara = new javax.swing.JLabel();
        jumpscareBonnie = new javax.swing.JPanel();
        jsBon = new javax.swing.JLabel();
        jumpscareChica = new javax.swing.JPanel();
        jsChica = new javax.swing.JLabel();
        jumpscareFreddysinLuz = new javax.swing.JPanel();
        jsFred = new javax.swing.JLabel();
        jumpscareFoxy = new javax.swing.JPanel();
        jsFox = new javax.swing.JLabel();
        jumpscareFredNormal = new javax.swing.JPanel();
        jsFreddyN = new javax.swing.JLabel();
        jumpscareGF = new javax.swing.JPanel();
        jsGF = new javax.swing.JLabel();
        BadEnding = new javax.swing.JPanel();
        bade = new javax.swing.JLabel();
        GoodEnding = new javax.swing.JPanel();
        goode = new javax.swing.JLabel();
        PantallaNegra = new javax.swing.JPanel();
        pantallan = new javax.swing.JLabel();
        GameOver = new javax.swing.JPanel();
        GO = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        JCB_LogIn = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JLbtnCrearUser = new javax.swing.JLabel();
        JLbtnCrearUser1 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLbtnContinuarNoche.setFont(new java.awt.Font("Verdana", 0, 26)); // NOI18N
        JLbtnContinuarNoche.setForeground(new java.awt.Color(255, 255, 255));
        JLbtnContinuarNoche.setText("Continuar Noche");
        jPanel2.add(JLbtnContinuarNoche, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 220, 40));

        JLbtnNuevaPartida.setFont(new java.awt.Font("Verdana", 0, 26)); // NOI18N
        JLbtnNuevaPartida.setForeground(new java.awt.Color(255, 255, 255));
        JLbtnNuevaPartida.setText("Nueva Partida");
        jPanel2.add(JLbtnNuevaPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 200, 40));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Five");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 80, 50));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nights");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 130, 70));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("at");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 50, 50));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Freddy´s");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 170, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/me srive (1).gif"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        javax.swing.GroupLayout vMenuJuegoLayout = new javax.swing.GroupLayout(vMenuJuego.getContentPane());
        vMenuJuego.getContentPane().setLayout(vMenuJuegoLayout);
        vMenuJuegoLayout.setHorizontalGroup(
            vMenuJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        vMenuJuegoLayout.setVerticalGroup(
            vMenuJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userLabel3.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        userLabel3.setForeground(new java.awt.Color(255, 255, 255));
        userLabel3.setText("Crear");
        jPanel3.add(userLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        Jtxtf_UsuarioAdd.setBackground(new java.awt.Color(0, 0, 0));
        Jtxtf_UsuarioAdd.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        Jtxtf_UsuarioAdd.setForeground(new java.awt.Color(255, 255, 255));
        Jtxtf_UsuarioAdd.setBorder(null);
        Jtxtf_UsuarioAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtxtf_UsuarioAddActionPerformed(evt);
            }
        });
        jPanel3.add(Jtxtf_UsuarioAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 500, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 510, 20));

        userLabel4.setFont(new java.awt.Font("Roboto Light", 1, 36)); // NOI18N
        userLabel4.setForeground(new java.awt.Color(255, 255, 255));
        userLabel4.setText("CREAR USUARIO");
        jPanel3.add(userLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        javax.swing.GroupLayout vCrearUsuarioLayout = new javax.swing.GroupLayout(vCrearUsuario.getContentPane());
        vCrearUsuario.getContentPane().setLayout(vCrearUsuarioLayout);
        vCrearUsuarioLayout.setHorizontalGroup(
            vCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 969, Short.MAX_VALUE)
        );
        vCrearUsuarioLayout.setVerticalGroup(
            vCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLbtnNochePers1.setFont(new java.awt.Font("Verdana", 0, 26)); // NOI18N
        JLbtnNochePers1.setForeground(new java.awt.Color(255, 255, 255));
        JLbtnNochePers1.setText("Noche Personalizada");
        jPanel4.add(JLbtnNochePers1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 280, 40));

        btnContinuarNocheAdmin.setFont(new java.awt.Font("Verdana", 0, 26)); // NOI18N
        btnContinuarNocheAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnContinuarNocheAdmin.setText("Continuar Noche");
        jPanel4.add(btnContinuarNocheAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 220, 40));

        JLbtnNuevaPartidaAdmin.setFont(new java.awt.Font("Verdana", 0, 26)); // NOI18N
        JLbtnNuevaPartidaAdmin.setForeground(new java.awt.Color(255, 255, 255));
        JLbtnNuevaPartidaAdmin.setText("Nueva Partida");
        JLbtnNuevaPartidaAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLbtnNuevaPartidaAdminMouseClicked(evt);
            }
        });
        jPanel4.add(JLbtnNuevaPartidaAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 200, 40));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Five");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 80, 50));

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nights");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 130, 70));

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("at");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 50, 50));

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Freddy´s");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 170, 60));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/me srive (1).gif"))); // NOI18N
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        javax.swing.GroupLayout vMenuJuegoAdminLayout = new javax.swing.GroupLayout(vMenuJuegoAdmin.getContentPane());
        vMenuJuegoAdmin.getContentPane().setLayout(vMenuJuegoAdminLayout);
        vMenuJuegoAdminLayout.setHorizontalGroup(
            vMenuJuegoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        vMenuJuegoAdminLayout.setVerticalGroup(
            vMenuJuegoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        vOficina.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        oficina.setBackground(new java.awt.Color(0, 0, 0));
        oficina.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbHora.setBackground(new java.awt.Color(255, 255, 255));
        lbHora.setFont(new java.awt.Font("Five Fonts at Freddy's", 0, 24)); // NOI18N
        lbHora.setForeground(new java.awt.Color(255, 255, 255));
        lbHora.setText("12 AM");
        oficina.add(lbHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 10, 80, 60));

        btn_luzder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_luzderMouseClicked(evt);
            }
        });
        oficina.add(btn_luzder, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 330, 50, 70));
        oficina.add(ventanader, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 70, 110, 360));
        oficina.add(ventanaizq, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 110, 360));

        btn_luzizq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_luzizqMouseClicked(evt);
            }
        });
        oficina.add(btn_luzizq, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 50, 70));

        btn_puertader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_puertaderMouseClicked(evt);
            }
        });
        oficina.add(btn_puertader, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 240, 60, 70));

        btn_puertaizq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_puertaizqMouseClicked(evt);
            }
        });
        oficina.add(btn_puertaizq, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 50, 70));

        btn_opencam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/barra1.jpeg"))); // NOI18N
        btn_opencam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_opencamMouseEntered(evt);
            }
        });
        oficina.add(btn_opencam, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 600, 520, 40));
        oficina.add(puertizq, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 230, 650));
        oficina.add(puertaLuzizq, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 230, 650));
        oficina.add(puertder, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 0, 200, 650));
        oficina.add(puertaLuzder, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 0, 200, 650));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ofi.jpg"))); // NOI18N
        oficina.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 650));

        vOficina.getContentPane().add(oficina, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        cam.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        monitor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/monitorAbfinal.gif"))); // NOI18N
        monitor.setPreferredSize(new java.awt.Dimension(1463, 650));
        cam.add(monitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1470, 650));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ofi.jpg"))); // NOI18N
        cam.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        vOficina.getContentPane().add(cam, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, -4, 1460, 650));

        camCerrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        monitor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/monitorcFinal.gif"))); // NOI18N
        camCerrar.add(monitor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1460, 650));

        fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ofi.jpg"))); // NOI18N
        camCerrar.add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        vOficina.getContentPane().add(camCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, -4, 1460, 650));

        povcam.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbHoraCam.setBackground(new java.awt.Color(255, 255, 255));
        lbHoraCam.setFont(new java.awt.Font("Five Fonts at Freddy's", 0, 24)); // NOI18N
        lbHoraCam.setForeground(new java.awt.Color(255, 255, 255));
        lbHoraCam.setText("12 AM");
        povcam.add(lbHoraCam, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 10, 80, 60));

        btn_Cam1A.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Cam1AMouseClicked(evt);
            }
        });
        povcam.add(btn_Cam1A, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 290, 60, 40));

        btn_Cam1B.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Cam1BMouseClicked(evt);
            }
        });
        povcam.add(btn_Cam1B, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 340, 60, 40));

        btn_Cam1C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Cam1CMouseClicked(evt);
            }
        });
        povcam.add(btn_Cam1C, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 420, 60, 40));

        btn_Cam2A.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Cam2AMouseClicked(evt);
            }
        });
        povcam.add(btn_Cam2A, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 540, 50, 30));

        btn_Cam2B.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Cam2BMouseClicked(evt);
            }
        });
        povcam.add(btn_Cam2B, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 580, 50, 30));

        btn_Cam3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Cam3MouseClicked(evt);
            }
        });
        povcam.add(btn_Cam3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 520, 60, 40));

        btn_Cam4A.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Cam4AMouseClicked(evt);
            }
        });
        povcam.add(btn_Cam4A, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 540, 50, 30));

        btn_Cam4B.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Cam4BMouseClicked(evt);
            }
        });
        povcam.add(btn_Cam4B, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 580, 50, 30));

        btn_Cam5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Cam5MouseClicked(evt);
            }
        });
        povcam.add(btn_Cam5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 370, 60, 40));

        btn_Cam6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Cam6MouseClicked(evt);
            }
        });
        povcam.add(btn_Cam6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 500, 60, 40));

        btn_Cam7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Cam7MouseClicked(evt);
            }
        });
        povcam.add(btn_Cam7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 370, 60, 40));

        btn_closecam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/barra1.jpeg"))); // NOI18N
        btn_closecam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_closecamMouseEntered(evt);
            }
        });
        povcam.add(btn_closecam, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 600, 520, 40));

        lbMapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mapap.png"))); // NOI18N
        povcam.add(lbMapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 290, 410, 340));

        setearCamara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/showstage_todos.jpg"))); // NOI18N
        povcam.add(setearCamara, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 650));

        vOficina.getContentPane().add(povcam, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, -4, 1470, 650));

        jsBon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/jsBonnie.gif"))); // NOI18N

        javax.swing.GroupLayout jumpscareBonnieLayout = new javax.swing.GroupLayout(jumpscareBonnie);
        jumpscareBonnie.setLayout(jumpscareBonnieLayout);
        jumpscareBonnieLayout.setHorizontalGroup(
            jumpscareBonnieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsBon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jumpscareBonnieLayout.setVerticalGroup(
            jumpscareBonnieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsBon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        vOficina.getContentPane().add(jumpscareBonnie, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jsChica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/jsChica.gif"))); // NOI18N

        javax.swing.GroupLayout jumpscareChicaLayout = new javax.swing.GroupLayout(jumpscareChica);
        jumpscareChica.setLayout(jumpscareChicaLayout);
        jumpscareChicaLayout.setHorizontalGroup(
            jumpscareChicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsChica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jumpscareChicaLayout.setVerticalGroup(
            jumpscareChicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsChica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        vOficina.getContentPane().add(jumpscareChica, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jsFred.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/jsFreddy.gif"))); // NOI18N

        javax.swing.GroupLayout jumpscareFreddysinLuzLayout = new javax.swing.GroupLayout(jumpscareFreddysinLuz);
        jumpscareFreddysinLuz.setLayout(jumpscareFreddysinLuzLayout);
        jumpscareFreddysinLuzLayout.setHorizontalGroup(
            jumpscareFreddysinLuzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsFred, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jumpscareFreddysinLuzLayout.setVerticalGroup(
            jumpscareFreddysinLuzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsFred, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        vOficina.getContentPane().add(jumpscareFreddysinLuz, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jsFox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/jsFoxy.gif"))); // NOI18N

        javax.swing.GroupLayout jumpscareFoxyLayout = new javax.swing.GroupLayout(jumpscareFoxy);
        jumpscareFoxy.setLayout(jumpscareFoxyLayout);
        jumpscareFoxyLayout.setHorizontalGroup(
            jumpscareFoxyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsFox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jumpscareFoxyLayout.setVerticalGroup(
            jumpscareFoxyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsFox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        vOficina.getContentPane().add(jumpscareFoxy, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout jumpscareFredNormalLayout = new javax.swing.GroupLayout(jumpscareFredNormal);
        jumpscareFredNormal.setLayout(jumpscareFredNormalLayout);
        jumpscareFredNormalLayout.setHorizontalGroup(
            jumpscareFredNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsFreddyN, javax.swing.GroupLayout.DEFAULT_SIZE, 1463, Short.MAX_VALUE)
        );
        jumpscareFredNormalLayout.setVerticalGroup(
            jumpscareFredNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsFreddyN, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        vOficina.getContentPane().add(jumpscareFredNormal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout jumpscareGFLayout = new javax.swing.GroupLayout(jumpscareGF);
        jumpscareGF.setLayout(jumpscareGFLayout);
        jumpscareGFLayout.setHorizontalGroup(
            jumpscareGFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsGF, javax.swing.GroupLayout.DEFAULT_SIZE, 1463, Short.MAX_VALUE)
        );
        jumpscareGFLayout.setVerticalGroup(
            jumpscareGFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsGF, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        vOficina.getContentPane().add(jumpscareGF, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        bade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/badDSPCN.jpg"))); // NOI18N

        javax.swing.GroupLayout BadEndingLayout = new javax.swing.GroupLayout(BadEnding);
        BadEnding.setLayout(BadEndingLayout);
        BadEndingLayout.setHorizontalGroup(
            BadEndingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BadEndingLayout.setVerticalGroup(
            BadEndingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        vOficina.getContentPane().add(BadEnding, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        goode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/goodDSP5.jpg"))); // NOI18N

        javax.swing.GroupLayout GoodEndingLayout = new javax.swing.GroupLayout(GoodEnding);
        GoodEnding.setLayout(GoodEndingLayout);
        GoodEndingLayout.setHorizontalGroup(
            GoodEndingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(goode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        GoodEndingLayout.setVerticalGroup(
            GoodEndingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(goode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        vOficina.getContentPane().add(GoodEnding, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout PantallaNegraLayout = new javax.swing.GroupLayout(PantallaNegra);
        PantallaNegra.setLayout(PantallaNegraLayout);
        PantallaNegraLayout.setHorizontalGroup(
            PantallaNegraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pantallan, javax.swing.GroupLayout.DEFAULT_SIZE, 1463, Short.MAX_VALUE)
        );
        PantallaNegraLayout.setVerticalGroup(
            PantallaNegraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pantallan, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        vOficina.getContentPane().add(PantallaNegra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        GO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gameOver.jpg"))); // NOI18N

        javax.swing.GroupLayout GameOverLayout = new javax.swing.GroupLayout(GameOver);
        GameOver.setLayout(GameOverLayout);
        GameOverLayout.setHorizontalGroup(
            GameOverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        GameOverLayout.setVerticalGroup(
            GameOverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        vOficina.getContentPane().add(GameOver, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        JCB_LogIn.setBackground(new java.awt.Color(0, 0, 0));
        JCB_LogIn.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setText("Log-In");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/helpy-fnaf-unscreen.gif"))); // NOI18N

        JLbtnCrearUser.setFont(new java.awt.Font("Verdana", 0, 30)); // NOI18N
        JLbtnCrearUser.setForeground(new java.awt.Color(255, 255, 255));
        JLbtnCrearUser.setText("Crear Usuario");
        JLbtnCrearUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLbtnCrearUserMouseClicked(evt);
            }
        });

        JLbtnCrearUser1.setFont(new java.awt.Font("Verdana", 0, 30)); // NOI18N
        JLbtnCrearUser1.setForeground(new java.awt.Color(255, 255, 255));
        JLbtnCrearUser1.setText("Entrar como Administrador");
        JLbtnCrearUser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLbtnCrearUser1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLbtnCrearUser1)
                    .addComponent(JLbtnCrearUser, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCB_LogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(64, 64, 64)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JLbtnCrearUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(JLbtnCrearUser, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JCB_LogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JLbtnCrearUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLbtnCrearUserMouseClicked
        this.setVisible(false);
        vCrearUsuario.pack();
        vCrearUsuario.setLocationRelativeTo(null);
        vCrearUsuario.setVisible(true);


    }//GEN-LAST:event_JLbtnCrearUserMouseClicked

    private void Jtxtf_UsuarioAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtxtf_UsuarioAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtxtf_UsuarioAddActionPerformed

    private void JLbtnCrearUser1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLbtnCrearUser1MouseClicked

        this.setVisible(false);
        vMenuJuegoAdmin.pack();
        vMenuJuegoAdmin.setLocationRelativeTo(null);
        vMenuJuegoAdmin.setVisible(true);

    }//GEN-LAST:event_JLbtnCrearUser1MouseClicked

    private void JLbtnNuevaPartidaAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLbtnNuevaPartidaAdminMouseClicked

        vMenuJuegoAdmin.setVisible(false);
        vOficina.pack();
        vOficina.setLocationRelativeTo(null);
        vOficina.setVisible(true);
        cam.setVisible(false);
        camCerrar.setVisible(false);
        puertizq.setVisible(false);
        //puertizq1.setVisible(false);
        puertder.setVisible(false);
        povcam.setVisible(false);
        jumpscareBonnie.setVisible(false);
        jumpscareChica.setVisible(false);
        jumpscareFreddysinLuz.setVisible(false);
        jumpscareFoxy.setVisible(false);
        jumpscareGF.setVisible(false);

        HiloHora hHora = new HiloHora(lbHora, lbHoraCam);
//        Noche1 no = new Noche1(setearCamara, locationCamara, this);
        hHora.start();
        Thread noche = new Thread(this);
        noche.start();
//        no.start();

    }//GEN-LAST:event_JLbtnNuevaPartidaAdminMouseClicked

    private void btn_opencamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_opencamMouseEntered
        //hiloMon.start();
        banderaCamara = 1; //
        HiloCamAnimation hCam = new HiloCamAnimation(cam, oficina, povcam);
        hCam.start();

    }//GEN-LAST:event_btn_opencamMouseEntered

    private void btn_puertaizqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_puertaizqMouseClicked
        //int bandera = 0; //abierta
        //int bandera = 1 cerrada

        if (banderaPuertaIz == 0) { //CERRAR
            HiloCloseDoor hCD = new HiloCloseDoor(puertizq);
            ImageIcon btnverdeiz = new ImageIcon(getClass().getResource("/Imagenes/btnVerdeIz.jpg"));
            btn_puertaizq.setIcon(btnverdeiz);
            hCD.start();
            banderaPuertaIz = 1;
        } else if (banderaPuertaIz == 1) {
            HiloOpenDoor hOD = new HiloOpenDoor(puertizq);
            //ImageIcon btnverdeiz = new ImageIcon(getClass().getResource("/Imagenes/btnVerdeIz"));
            btn_puertaizq.setIcon(null);
            hOD.start();
            banderaPuertaIz = 0;
        }


    }//GEN-LAST:event_btn_puertaizqMouseClicked

    private void btn_puertaderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_puertaderMouseClicked
        //int bandera = 0; //abierta
        //int bandera = 1 cerrada

        if (banderaPuertaDer == 0) { //CERRAR
            HiloCloseDoorDerecha hCD = new HiloCloseDoorDerecha(puertder);
            ImageIcon btnverdeiz = new ImageIcon(getClass().getResource("/Imagenes/btnVerdeDer.jpg"));
            btn_puertader.setIcon(btnverdeiz);
            hCD.start();
            banderaPuertaDer = 1;
        } else if (banderaPuertaDer == 1) { //abrir
            HiloOpenDoorDerecha hOD = new HiloOpenDoorDerecha(puertder);
            //ImageIcon btnverdeiz = new ImageIcon(getClass().getResource("/Imagenes/btnVerdeIz"));
            btn_puertader.setIcon(null);
            hOD.start();
            banderaPuertaDer = 0;
        }
    }//GEN-LAST:event_btn_puertaderMouseClicked

    private void btn_closecamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closecamMouseEntered
        banderaCamara = 0;
        HiloCloseCam hCloseCam = new HiloCloseCam(camCerrar, oficina, povcam);
        hCloseCam.start();
    }//GEN-LAST:event_btn_closecamMouseEntered

    private void btn_Cam1AMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cam1AMouseClicked
        locationCamara = "stage";
        System.out.println(locationCamara);
    }//GEN-LAST:event_btn_Cam1AMouseClicked

    private void btn_Cam1BMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cam1BMouseClicked
        locationCamara = "dinning";
        //System.out.println(locationCamara);
    }//GEN-LAST:event_btn_Cam1BMouseClicked

    private void btn_Cam1CMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cam1CMouseClicked
        locationCamara = "pirateCove";
        //System.out.println(locationCamara);
    }//GEN-LAST:event_btn_Cam1CMouseClicked

    private void btn_Cam2AMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cam2AMouseClicked
        locationCamara = "wHall";
    }//GEN-LAST:event_btn_Cam2AMouseClicked

    private void btn_Cam2BMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cam2BMouseClicked
        locationCamara = "wHallCorner";
    }//GEN-LAST:event_btn_Cam2BMouseClicked

    private void btn_Cam3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cam3MouseClicked
        locationCamara = "supplyCloset";
    }//GEN-LAST:event_btn_Cam3MouseClicked

    private void btn_Cam4AMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cam4AMouseClicked
        locationCamara = "eHall";
    }//GEN-LAST:event_btn_Cam4AMouseClicked

    private void btn_Cam4BMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cam4BMouseClicked
        locationCamara = "eHallCorner";
    }//GEN-LAST:event_btn_Cam4BMouseClicked

    private void btn_Cam5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cam5MouseClicked
        locationCamara = "backstage";
    }//GEN-LAST:event_btn_Cam5MouseClicked

    private void btn_Cam6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cam6MouseClicked
        locationCamara = "kitchen"; //CAM DISABLE
    }//GEN-LAST:event_btn_Cam6MouseClicked

    private void btn_Cam7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cam7MouseClicked
        locationCamara = "restrooms";
    }//GEN-LAST:event_btn_Cam7MouseClicked

    private void btn_luzizqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_luzizqMouseClicked
        if (banderaLuzIz == 0) { //ENCENDER
            ImageIcon btnluzder = new ImageIcon(getClass().getResource("/Imagenes/luzbtnIzq.jpg"));
            ImageIcon btnluzPuertader = new ImageIcon(getClass().getResource("/Imagenes/puertaIzqLuz.jpg"));
            ImageIcon btnluzVentanader = new ImageIcon(getClass().getResource("/Imagenes/ventanaIzqLuz.png"));
            btn_luzizq.setIcon(btnluzder);
            puertaLuzizq.setIcon(btnluzPuertader);
            ventanaizq.setIcon(btnluzVentanader);
            banderaLuzIz = 1;
        } else if (banderaLuzIz == 1) { //APAGAR
            //ImageIcon btnverdeiz = new ImageIcon(getClass().getResource("/Imagenes/btnVerdeIz"));
            btn_luzizq.setIcon(null);
            puertaLuzizq.setIcon(null);
            ventanaizq.setIcon(null);
            banderaLuzIz = 0;
        }
    }//GEN-LAST:event_btn_luzizqMouseClicked

    private void btn_luzderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_luzderMouseClicked

        if (banderaLuzDer == 0) { //ENCENDER
            ImageIcon btnluzder = new ImageIcon(getClass().getResource("/Imagenes/luzbtnDer.jpg"));
            ImageIcon btnluzPuertader = new ImageIcon(getClass().getResource("/Imagenes/puertaDerLuzeEn.jpg"));
            ImageIcon btnluzVentanader = new ImageIcon(getClass().getResource("/Imagenes/venDerLuz.png"));
            btn_luzder.setIcon(btnluzder);
            puertaLuzder.setIcon(btnluzPuertader);
            ventanader.setIcon(btnluzVentanader);
            banderaLuzDer = 1;
        } else if (banderaLuzDer == 1) { //APAGAR
            //ImageIcon btnverdeiz = new ImageIcon(getClass().getResource("/Imagenes/btnVerdeIz"));
            btn_luzder.setIcon(null);
            puertaLuzder.setIcon(null);
            ventanader.setIcon(null);
            banderaLuzDer = 0;
        }

    }//GEN-LAST:event_btn_luzderMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    public void SetImage(JLabel labelname, String root) {

        ImageIcon imagen = new ImageIcon(root);
        Icon icon = new ImageIcon(imagen.getImage().getScaledInstance(labelname.getWidth(), labelname.getHeight(), Image.SCALE_DEFAULT));
        labelname.setIcon(icon);
        this.repaint();

    }

    public void llenarMisCuentasList() {

        //Array del tamaño de usuarios creados
        String[] user = new String[usuarios.size()];
        int i = 0;
        //Recorro mi arrayList de usuarios
        for (Usuario u : usuarios) {
            user[i] = u.getUsuario();
            i++;
        }

        //Lleno el comboBox
        JCB_LogIn.setModel(new DefaultComboBoxModel(user)); //
    }

    public JLabel getSetearCamara() {
        return setearCamara;
    }

    public void setSetearCamara(Icon ic) {
        this.setearCamara.setIcon(ic);
    }

    public String getNombreCam() {
        return locationCamara;
    }

    public void setNombreCam(String locCamara) {
        this.locationCamara = locCamara;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BadEnding;
    private javax.swing.JLabel GO;
    private javax.swing.JPanel GameOver;
    private javax.swing.JPanel GoodEnding;
    private javax.swing.JComboBox<String> JCB_LogIn;
    private javax.swing.JLabel JLbtnContinuarNoche;
    private javax.swing.JLabel JLbtnCrearUser;
    private javax.swing.JLabel JLbtnCrearUser1;
    private javax.swing.JLabel JLbtnNochePers1;
    private javax.swing.JLabel JLbtnNuevaPartida;
    private javax.swing.JLabel JLbtnNuevaPartidaAdmin;
    private javax.swing.JTextField Jtxtf_UsuarioAdd;
    private javax.swing.JPanel PantallaNegra;
    private javax.swing.JLabel bade;
    private javax.swing.JLabel btnContinuarNocheAdmin;
    private javax.swing.JLabel btn_Cam1A;
    private javax.swing.JLabel btn_Cam1B;
    private javax.swing.JLabel btn_Cam1C;
    private javax.swing.JLabel btn_Cam2A;
    private javax.swing.JLabel btn_Cam2B;
    private javax.swing.JLabel btn_Cam3;
    private javax.swing.JLabel btn_Cam4A;
    private javax.swing.JLabel btn_Cam4B;
    private javax.swing.JLabel btn_Cam5;
    private javax.swing.JLabel btn_Cam6;
    private javax.swing.JLabel btn_Cam7;
    private javax.swing.JLabel btn_closecam;
    private javax.swing.JLabel btn_luzder;
    private javax.swing.JLabel btn_luzizq;
    private javax.swing.JLabel btn_opencam;
    private javax.swing.JLabel btn_puertader;
    private javax.swing.JLabel btn_puertaizq;
    private javax.swing.JPanel cam;
    private javax.swing.JPanel camCerrar;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondo1;
    private javax.swing.JLabel goode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jsBon;
    private javax.swing.JLabel jsChica;
    private javax.swing.JLabel jsFox;
    private javax.swing.JLabel jsFred;
    private javax.swing.JLabel jsFreddyN;
    private javax.swing.JLabel jsGF;
    private javax.swing.JPanel jumpscareBonnie;
    private javax.swing.JPanel jumpscareChica;
    private javax.swing.JPanel jumpscareFoxy;
    private javax.swing.JPanel jumpscareFredNormal;
    private javax.swing.JPanel jumpscareFreddysinLuz;
    private javax.swing.JPanel jumpscareGF;
    private javax.swing.JLabel lbHora;
    private javax.swing.JLabel lbHoraCam;
    private javax.swing.JLabel lbMapa;
    private javax.swing.JLabel monitor;
    private javax.swing.JLabel monitor1;
    private javax.swing.JPanel oficina;
    private javax.swing.JLabel pantallan;
    private javax.swing.JPanel povcam;
    private javax.swing.JLabel puertaLuzder;
    private javax.swing.JLabel puertaLuzizq;
    private javax.swing.JLabel puertder;
    private javax.swing.JLabel puertizq;
    private javax.swing.JLabel setearCamara;
    private javax.swing.JLabel userLabel3;
    private javax.swing.JLabel userLabel4;
    private javax.swing.JDialog vCrearUsuario;
    private javax.swing.JDialog vMenuJuego;
    private javax.swing.JDialog vMenuJuegoAdmin;
    private javax.swing.JFrame vOficina;
    private javax.swing.JLabel ventanader;
    private javax.swing.JLabel ventanaizq;
    // End of variables declaration//GEN-END:variables

    private int contador = 0;
    private int contador2 = 0;
    private boolean isAlive = true;
    private Bonnie bon = new Bonnie(3);
    private Chica chic = new Chica(7);

    @Override
    public void run() {

        while (isAlive) {
            contador2++;

            try {
                Thread.sleep(1);
            } catch (Exception e) {
            }
            System.out.println("");
            System.out.println(contador2);
            System.out.println(contador);
            System.out.println();
            if (contador2 == 4000) {
                bon.movimiento();
                chic.movimiento();
                contador2 = 0;
            }

            System.out.println("Bonnie pos: " + bon.getUbic());
            System.out.println();
            System.out.println("Chica pos: " + chic.getUbic());

            if (locationCamara.equals("stage")) { // 1A
                if (bon.getUbic() == 0 && chic.getUbic() == 0) { //estan los tres
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/showstage_todos.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }
                if (bon.getUbic() != 0 && chic.getUbic() == 0) { //estan sin bonnie
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/SHSsinBonnie.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }
                if (bon.getUbic() == 0 && chic.getUbic() != 0) { //estan sin chica
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/SHSsinChica.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }
                if (bon.getUbic() != 0 && chic.getUbic() != 0) { //solo freddy
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/SHSSOLOFreddy.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }

            }

            if (locationCamara.equals("dinning")) { //1, 2 BONNIE Y CHICA //FREDDY SOLO 1 // bon 1 2 / chic 1 2 / fred 1 //1B

                if (bon.getUbic() != 1 && chic.getUbic() != 1 && chic.getUbic() != 2 && bon.getUbic() != 2) { //vacio
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/DinnerVacio.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }
                if (bon.getUbic() == 1 && chic.getUbic() != 1 && chic.getUbic() != 2 && bon.getUbic() != 2) { //bonnie 1
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/DinnerBonnie1.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }
                if (bon.getUbic() != 1 && chic.getUbic() != 1 && chic.getUbic() != 2 && bon.getUbic() == 2) { //bonnie 2
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/DinningBonnie2.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }
                if (bon.getUbic() != 1 && chic.getUbic() == 1 && chic.getUbic() != 2 && bon.getUbic() != 2) { //chica 1
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/DinnerChica1.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }
                if (bon.getUbic() != 1 && chic.getUbic() != 1 && chic.getUbic() == 2 && bon.getUbic() != 2) { //chica 2
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/DinnerChica2.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }
                if ((bon.getUbic() == 1 && chic.getUbic() == 1) || (chic.getUbic() == 2 && bon.getUbic() == 2)) { //si estan bonnie y chica
                    bon.setUbic(3);
                }
                if ((bon.getUbic() == 1 && chic.getUbic() == 2) || (chic.getUbic() == 1 && bon.getUbic() == 2)) { //si estan bonnie y 
                    bon.setUbic(3);
                }

            }

            if (locationCamara.equals("pirateCove")) { //FOXY 0 1 2 y si se fue // 1C
                ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/PirateC_0.jpg"));
                setearCamara.setIcon(showstage_todos);
            }

            if (locationCamara.equals("wHall")) { // gif fox 3 / bon 5 //2A

                if (bon.getUbic() != 5) { //VACIO
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/wHallVacio.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }
                if (bon.getUbic() == 5) { //BONNIE /tiene 7 posiciones creo
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/wHallBonnie.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }

            }

            if (locationCamara.equals("wHallCorner")) { //bon 7 // gf no se //2B

                if (bon.getUbic() != 7) { //VACIO
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/wHallCVacio.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }
                if (bon.getUbic() == 7) { //bonnie
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/wHallCBon.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }

            }

            if (locationCamara.equals("supplyCloset")) { // bon 6         //3

                if (bon.getUbic() != 6) { //VACIO
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/ClosetVacio.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }
                if (bon.getUbic() == 6) { //bonnie
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/ClosetBon.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }

            }

            if (locationCamara.equals("eHall")) { //chic 6 7 / fred 3 //4A

                if (chic.getUbic() != 6 && chic.getUbic() != 7) { //VACIO
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/eHallVacio.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }
                if (chic.getUbic() == 6 && chic.getUbic() != 7) { //CHICA
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/eHallChica6.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }
                if (chic.getUbic() != 6 && chic.getUbic() == 7) { //CHICA CERCA
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/eHallChica7.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }
            }

            if (locationCamara.equals("eHallCorner")) { //chic 8 / fred 4 //4B

                if (chic.getUbic() != 8) { //vacio
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/eHallCornerVacio.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }
                if (chic.getUbic() == 8) { //chica
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/eHallCornerChica.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }

            }

            if (locationCamara.equals("backstage")) { //bon 3 4            //5

                if (bon.getUbic() != 3 && bon.getUbic() != 4) { //vacio
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/backstVacio.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }
                if (bon.getUbic() == 3 && bon.getUbic() != 4) { //bonnie
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/backstBonnie1.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }
                if (bon.getUbic() != 3 && bon.getUbic() == 4) { //bonnie
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/backstBonnie2.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }

            }

            if (locationCamara.equals("kitchen")) { //chic 5            //6
                //camara desabilitada
                ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/static.gif"));
                setearCamara.setIcon(showstage_todos);

            }

            if (locationCamara.equals("restrooms")) { //chic 3 4 / fred 2     //7

                if (chic.getUbic() != 3 && chic.getUbic() != 4) { //VACIO
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/restroomVacio.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }
                if (chic.getUbic() == 3 && chic.getUbic() != 4) { //CHICA
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/restroomChica1.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }
                if (chic.getUbic() != 3 && chic.getUbic() == 4) { //CHICA CERCA
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/restroomChica2.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }

            }

            if (banderaLuzDer == 1 && chic.getUbic() == 9) {
                ImageIcon btnluzVentanader = new ImageIcon(getClass().getResource("/Imagenes/venDerLuzChica2.png"));
                ventanader.setIcon(btnluzVentanader);
            }

            if (banderaLuzIz == 1 && bon.getUbic() == 8) {
                ImageIcon btnluzPuertader = new ImageIcon(getClass().getResource("/Imagenes/bonofiLuzEn.jpg"));
                puertaLuzizq.setIcon(btnluzPuertader);
            }

            if (bon.getUbic() == 8 && banderaPuertaIz == 0 && banderaCamara == 0) {
                HiloJumpscareB hJSBon = new HiloJumpscareB(jumpscareBonnie, this, vOficina, oficina);
                hJSBon.start();
                return;
            }
            
            if (chic.getUbic() == 9 && banderaPuertaDer == 0 && banderaCamara == 0) {
                HiloJSChica hJSChic = new HiloJSChica(jumpscareBonnie, this, vOficina, oficina);
                hJSChic.start();
                return;
            }
            
            if (chic.getUbic() == 9 && banderaPuertaDer == 1) {
                chic.setUbic(1);
            }
            
            if (bon.getUbic() == 8 && banderaPuertaIz == 1) {
                bon.setUbic(1);
            }

            contador++;
            if (contador == 180000) {
                isAlive = false;
                System.out.println("Fin hilo");
                return;
            }

        }
    }
}
