/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectofnaf_carmencastillo;

import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.TimerTask;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.Timer;

/**
 *
 * @author casti
 */
public class Main extends javax.swing.JFrame {

    private ArrayList<Usuario> usuarios;
    private int mouseX, mouseY;
    private int banderaPuertaIz = 0;
    private int banderaPuertaDer = 0;
    private int banderaLuzDer = 0;
    private int banderaLuzIz = 0;
    public String locationCamara;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();

        this.setLocationRelativeTo(null);
        this.setResizable(true);
        hHora = new HiloHora(lbHora, lbHoraCam);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vMenuJuego = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        JLbtnContinuarNoche = new javax.swing.JLabel();
        JLbtnNuevaPartida = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        vCrearUsuario = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        userLabel3 = new javax.swing.JLabel();
        Jtxtf_UsuarioAdd = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        userLabel4 = new javax.swing.JLabel();
        vMenuJuegoAdmin = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        JLbtnNochePers1 = new javax.swing.JLabel();
        btnContinuarNocheAdmin = new javax.swing.JLabel();
        JLbtnNuevaPartidaAdmin = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        vOficina = new javax.swing.JFrame();
        oficina = new javax.swing.JPanel();
        lbHora = new javax.swing.JLabel();
        btn_luzder = new javax.swing.JLabel();
        ventanader = new javax.swing.JLabel();
        ventanaizq = new javax.swing.JLabel();
        btn_luzizq = new javax.swing.JLabel();
        btn_puertader = new javax.swing.JLabel();
        btn_puertaizq = new javax.swing.JLabel();
        btn_opencam = new javax.swing.JLabel();
        puertizq = new javax.swing.JLabel();
        puertaLuzizq = new javax.swing.JLabel();
        puertder = new javax.swing.JLabel();
        puertaLuzder = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cam = new javax.swing.JPanel();
        monitor = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        camCerrar = new javax.swing.JPanel();
        monitor1 = new javax.swing.JLabel();
        fondo1 = new javax.swing.JLabel();
        povcam = new javax.swing.JPanel();
        lbHoraCam = new javax.swing.JLabel();
        btn_Cam1A = new javax.swing.JLabel();
        btn_Cam1B = new javax.swing.JLabel();
        btn_Cam1C = new javax.swing.JLabel();
        btn_Cam2A = new javax.swing.JLabel();
        btn_Cam2B = new javax.swing.JLabel();
        btn_Cam3 = new javax.swing.JLabel();
        btn_Cam4A = new javax.swing.JLabel();
        btn_Cam4B = new javax.swing.JLabel();
        btn_Cam5 = new javax.swing.JLabel();
        btn_Cam6 = new javax.swing.JLabel();
        btn_Cam7 = new javax.swing.JLabel();
        btn_closecam = new javax.swing.JLabel();
        lbMapa = new javax.swing.JLabel();
        setearCamara = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        JCB_LogIn = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JLbtnCrearUser = new javax.swing.JLabel();
        JLbtnCrearUser1 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLbtnContinuarNoche.setFont(new java.awt.Font("Verdana", 0, 26)); // NOI18N
        JLbtnContinuarNoche.setForeground(new java.awt.Color(255, 255, 255));
        JLbtnContinuarNoche.setText("Continuar Noche");
        jPanel2.add(JLbtnContinuarNoche, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 220, 40));

        JLbtnNuevaPartida.setFont(new java.awt.Font("Verdana", 0, 26)); // NOI18N
        JLbtnNuevaPartida.setForeground(new java.awt.Color(255, 255, 255));
        JLbtnNuevaPartida.setText("Nueva Partida");
        jPanel2.add(JLbtnNuevaPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 200, 40));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Five");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 80, 50));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nights");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 130, 70));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("at");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 50, 50));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Freddy´s");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 170, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/me srive (1).gif"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        javax.swing.GroupLayout vMenuJuegoLayout = new javax.swing.GroupLayout(vMenuJuego.getContentPane());
        vMenuJuego.getContentPane().setLayout(vMenuJuegoLayout);
        vMenuJuegoLayout.setHorizontalGroup(
            vMenuJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        vMenuJuegoLayout.setVerticalGroup(
            vMenuJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userLabel3.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        userLabel3.setForeground(new java.awt.Color(255, 255, 255));
        userLabel3.setText("Crear");
        jPanel3.add(userLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        Jtxtf_UsuarioAdd.setBackground(new java.awt.Color(0, 0, 0));
        Jtxtf_UsuarioAdd.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        Jtxtf_UsuarioAdd.setForeground(new java.awt.Color(255, 255, 255));
        Jtxtf_UsuarioAdd.setBorder(null);
        Jtxtf_UsuarioAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtxtf_UsuarioAddActionPerformed(evt);
            }
        });
        jPanel3.add(Jtxtf_UsuarioAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 500, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 510, 20));

        userLabel4.setFont(new java.awt.Font("Roboto Light", 1, 36)); // NOI18N
        userLabel4.setForeground(new java.awt.Color(255, 255, 255));
        userLabel4.setText("CREAR USUARIO");
        jPanel3.add(userLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        javax.swing.GroupLayout vCrearUsuarioLayout = new javax.swing.GroupLayout(vCrearUsuario.getContentPane());
        vCrearUsuario.getContentPane().setLayout(vCrearUsuarioLayout);
        vCrearUsuarioLayout.setHorizontalGroup(
            vCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 969, Short.MAX_VALUE)
        );
        vCrearUsuarioLayout.setVerticalGroup(
            vCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLbtnNochePers1.setFont(new java.awt.Font("Verdana", 0, 26)); // NOI18N
        JLbtnNochePers1.setForeground(new java.awt.Color(255, 255, 255));
        JLbtnNochePers1.setText("Noche Personalizada");
        jPanel4.add(JLbtnNochePers1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 280, 40));

        btnContinuarNocheAdmin.setFont(new java.awt.Font("Verdana", 0, 26)); // NOI18N
        btnContinuarNocheAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnContinuarNocheAdmin.setText("Continuar Noche");
        jPanel4.add(btnContinuarNocheAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 220, 40));

        JLbtnNuevaPartidaAdmin.setFont(new java.awt.Font("Verdana", 0, 26)); // NOI18N
        JLbtnNuevaPartidaAdmin.setForeground(new java.awt.Color(255, 255, 255));
        JLbtnNuevaPartidaAdmin.setText("Nueva Partida");
        JLbtnNuevaPartidaAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLbtnNuevaPartidaAdminMouseClicked(evt);
            }
        });
        jPanel4.add(JLbtnNuevaPartidaAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 200, 40));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Five");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 80, 50));

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nights");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 130, 70));

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("at");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 50, 50));

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Freddy´s");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 170, 60));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/me srive (1).gif"))); // NOI18N
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        javax.swing.GroupLayout vMenuJuegoAdminLayout = new javax.swing.GroupLayout(vMenuJuegoAdmin.getContentPane());
        vMenuJuegoAdmin.getContentPane().setLayout(vMenuJuegoAdminLayout);
        vMenuJuegoAdminLayout.setHorizontalGroup(
            vMenuJuegoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        vMenuJuegoAdminLayout.setVerticalGroup(
            vMenuJuegoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        vOficina.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        oficina.setBackground(new java.awt.Color(0, 0, 0));
        oficina.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbHora.setBackground(new java.awt.Color(255, 255, 255));
        lbHora.setFont(new java.awt.Font("Five Fonts at Freddy's", 0, 24)); // NOI18N
        lbHora.setForeground(new java.awt.Color(255, 255, 255));
        lbHora.setText("12 AM");
        oficina.add(lbHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 10, 80, 60));

        btn_luzder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_luzderMouseClicked(evt);
            }
        });
        oficina.add(btn_luzder, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 330, 50, 70));
        oficina.add(ventanader, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 70, 110, 360));
        oficina.add(ventanaizq, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 110, 360));

        btn_luzizq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_luzizqMouseClicked(evt);
            }
        });
        oficina.add(btn_luzizq, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 50, 70));

        btn_puertader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_puertaderMouseClicked(evt);
            }
        });
        oficina.add(btn_puertader, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 240, 60, 70));

        btn_puertaizq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_puertaizqMouseClicked(evt);
            }
        });
        oficina.add(btn_puertaizq, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 50, 70));

        btn_opencam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/barra1.jpeg"))); // NOI18N
        btn_opencam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_opencamMouseEntered(evt);
            }
        });
        oficina.add(btn_opencam, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 600, 520, 40));
        oficina.add(puertizq, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 230, 650));
        oficina.add(puertaLuzizq, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 230, 650));
        oficina.add(puertder, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 0, 200, 650));
        oficina.add(puertaLuzder, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 0, 200, 650));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ofi.jpg"))); // NOI18N
        oficina.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 650));

        vOficina.getContentPane().add(oficina, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        cam.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        monitor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/monitorAbfinal.gif"))); // NOI18N
        cam.add(monitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1470, 650));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ofi.jpg"))); // NOI18N
        cam.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        vOficina.getContentPane().add(cam, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, -4, 1460, 650));

        camCerrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        monitor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/monitorcFinal.gif"))); // NOI18N
        camCerrar.add(monitor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1460, 650));

        fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ofi.jpg"))); // NOI18N
        camCerrar.add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        vOficina.getContentPane().add(camCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, -4, 1460, 650));

        povcam.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbHoraCam.setBackground(new java.awt.Color(255, 255, 255));
        lbHoraCam.setFont(new java.awt.Font("Five Fonts at Freddy's", 0, 24)); // NOI18N
        lbHoraCam.setForeground(new java.awt.Color(255, 255, 255));
        lbHoraCam.setText("12 AM");
        povcam.add(lbHoraCam, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 10, 80, 60));

        btn_Cam1A.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Cam1AMouseClicked(evt);
            }
        });
        povcam.add(btn_Cam1A, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 290, 60, 40));

        btn_Cam1B.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Cam1BMouseClicked(evt);
            }
        });
        povcam.add(btn_Cam1B, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 340, 60, 40));

        btn_Cam1C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Cam1CMouseClicked(evt);
            }
        });
        povcam.add(btn_Cam1C, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 420, 60, 40));

        btn_Cam2A.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Cam2AMouseClicked(evt);
            }
        });
        povcam.add(btn_Cam2A, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 540, 50, 30));

        btn_Cam2B.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Cam2BMouseClicked(evt);
            }
        });
        povcam.add(btn_Cam2B, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 580, 50, 30));

        btn_Cam3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Cam3MouseClicked(evt);
            }
        });
        povcam.add(btn_Cam3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 520, 60, 40));

        btn_Cam4A.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Cam4AMouseClicked(evt);
            }
        });
        povcam.add(btn_Cam4A, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 540, 50, 30));

        btn_Cam4B.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Cam4BMouseClicked(evt);
            }
        });
        povcam.add(btn_Cam4B, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 580, 50, 30));

        btn_Cam5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Cam5MouseClicked(evt);
            }
        });
        povcam.add(btn_Cam5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 370, 60, 40));

        btn_Cam6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Cam6MouseClicked(evt);
            }
        });
        povcam.add(btn_Cam6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 500, 60, 40));

        btn_Cam7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Cam7MouseClicked(evt);
            }
        });
        povcam.add(btn_Cam7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 370, 60, 40));

        btn_closecam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/barra1.jpeg"))); // NOI18N
        btn_closecam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_closecamMouseEntered(evt);
            }
        });
        povcam.add(btn_closecam, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 600, 520, 40));

        lbMapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mapap.png"))); // NOI18N
        povcam.add(lbMapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 290, 410, 340));

        setearCamara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/showstage_todos.jpg"))); // NOI18N
        povcam.add(setearCamara, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 650));

        vOficina.getContentPane().add(povcam, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, -4, 1470, 650));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        JCB_LogIn.setBackground(new java.awt.Color(0, 0, 0));
        JCB_LogIn.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setText("Log-In");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/helpy-fnaf-unscreen.gif"))); // NOI18N

        JLbtnCrearUser.setFont(new java.awt.Font("Verdana", 0, 30)); // NOI18N
        JLbtnCrearUser.setForeground(new java.awt.Color(255, 255, 255));
        JLbtnCrearUser.setText("Crear Usuario");
        JLbtnCrearUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLbtnCrearUserMouseClicked(evt);
            }
        });

        JLbtnCrearUser1.setFont(new java.awt.Font("Verdana", 0, 30)); // NOI18N
        JLbtnCrearUser1.setForeground(new java.awt.Color(255, 255, 255));
        JLbtnCrearUser1.setText("Entrar como Administrador");
        JLbtnCrearUser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLbtnCrearUser1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLbtnCrearUser1)
                    .addComponent(JLbtnCrearUser, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCB_LogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(64, 64, 64)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JLbtnCrearUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(JLbtnCrearUser, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JCB_LogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JLbtnCrearUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLbtnCrearUserMouseClicked
        this.setVisible(false);
        vCrearUsuario.pack();
        vCrearUsuario.setLocationRelativeTo(null);
        vCrearUsuario.setVisible(true);


    }//GEN-LAST:event_JLbtnCrearUserMouseClicked

    private void Jtxtf_UsuarioAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtxtf_UsuarioAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtxtf_UsuarioAddActionPerformed

    private void JLbtnCrearUser1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLbtnCrearUser1MouseClicked

        this.setVisible(false);
        vMenuJuegoAdmin.pack();
        vMenuJuegoAdmin.setLocationRelativeTo(null);
        vMenuJuegoAdmin.setVisible(true);

    }//GEN-LAST:event_JLbtnCrearUser1MouseClicked

    private void JLbtnNuevaPartidaAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLbtnNuevaPartidaAdminMouseClicked

        vMenuJuegoAdmin.setVisible(false);
        vOficina.pack();
        vOficina.setLocationRelativeTo(null);
        vOficina.setVisible(true);
        cam.setVisible(false);
        camCerrar.setVisible(false);
        puertizq.setVisible(false);
        //puertizq1.setVisible(false);
        puertder.setVisible(false);
        povcam.setVisible(false);
        hHora.start();

    }//GEN-LAST:event_JLbtnNuevaPartidaAdminMouseClicked

    private void btn_opencamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_opencamMouseEntered
        //hiloMon.start();
        HiloCamAnimation hCam = new HiloCamAnimation(cam, oficina, povcam);
        hCam.start();

    }//GEN-LAST:event_btn_opencamMouseEntered

    private void btn_puertaizqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_puertaizqMouseClicked
        //int bandera = 0; //abierta
        //int bandera = 1 cerrada

        if (banderaPuertaIz == 0) { //CERRAR
            HiloCloseDoor hCD = new HiloCloseDoor(puertizq);
            ImageIcon btnverdeiz = new ImageIcon(getClass().getResource("/Imagenes/btnVerdeIz.jpg"));
            btn_puertaizq.setIcon(btnverdeiz);
            hCD.start();
            banderaPuertaIz = 1;
        } else if (banderaPuertaIz == 1) {
            HiloOpenDoor hOD = new HiloOpenDoor(puertizq);
            //ImageIcon btnverdeiz = new ImageIcon(getClass().getResource("/Imagenes/btnVerdeIz"));
            btn_puertaizq.setIcon(null);
            hOD.start();
            banderaPuertaIz = 0;
        }


    }//GEN-LAST:event_btn_puertaizqMouseClicked

    private void btn_puertaderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_puertaderMouseClicked
        //int bandera = 0; //abierta
        //int bandera = 1 cerrada

        if (banderaPuertaDer == 0) { //CERRAR
            HiloCloseDoorDerecha hCD = new HiloCloseDoorDerecha(puertder);
            ImageIcon btnverdeiz = new ImageIcon(getClass().getResource("/Imagenes/btnVerdeDer.jpg"));
            btn_puertader.setIcon(btnverdeiz);
            hCD.start();
            banderaPuertaDer = 1;
        } else if (banderaPuertaDer == 1) { //abrir
            HiloOpenDoorDerecha hOD = new HiloOpenDoorDerecha(puertder);
            //ImageIcon btnverdeiz = new ImageIcon(getClass().getResource("/Imagenes/btnVerdeIz"));
            btn_puertader.setIcon(null);
            hOD.start();
            banderaPuertaDer = 0;
        }
    }//GEN-LAST:event_btn_puertaderMouseClicked

    private void btn_closecamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closecamMouseEntered
        HiloCloseCam hCloseCam = new HiloCloseCam(camCerrar, oficina, povcam);
        hCloseCam.start();
    }//GEN-LAST:event_btn_closecamMouseEntered

    private void btn_Cam1AMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cam1AMouseClicked
        locationCamara = "stage";
    }//GEN-LAST:event_btn_Cam1AMouseClicked

    private void btn_Cam1BMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cam1BMouseClicked
        locationCamara = "dinning";
    }//GEN-LAST:event_btn_Cam1BMouseClicked

    private void btn_Cam1CMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cam1CMouseClicked
        locationCamara = "pirateCove";
    }//GEN-LAST:event_btn_Cam1CMouseClicked

    private void btn_Cam2AMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cam2AMouseClicked
        locationCamara = "wHall";
    }//GEN-LAST:event_btn_Cam2AMouseClicked

    private void btn_Cam2BMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cam2BMouseClicked
        locationCamara = "wHallCorner";
    }//GEN-LAST:event_btn_Cam2BMouseClicked

    private void btn_Cam3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cam3MouseClicked
        locationCamara = "supplyCloset";
    }//GEN-LAST:event_btn_Cam3MouseClicked

    private void btn_Cam4AMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cam4AMouseClicked
        locationCamara = "eHall";
    }//GEN-LAST:event_btn_Cam4AMouseClicked

    private void btn_Cam4BMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cam4BMouseClicked
        locationCamara = "eHallCorner";
    }//GEN-LAST:event_btn_Cam4BMouseClicked

    private void btn_Cam5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cam5MouseClicked
        locationCamara = "backstage";
    }//GEN-LAST:event_btn_Cam5MouseClicked

    private void btn_Cam6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cam6MouseClicked
        locationCamara = "kitchen"; //CAM DISABLE
    }//GEN-LAST:event_btn_Cam6MouseClicked

    private void btn_Cam7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cam7MouseClicked
        locationCamara = "restrooms";
    }//GEN-LAST:event_btn_Cam7MouseClicked

    private void btn_luzizqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_luzizqMouseClicked
        if (banderaLuzIz == 0) { //ENCENDER
            ImageIcon btnluzder = new ImageIcon(getClass().getResource("/Imagenes/luzbtnIzq.jpg"));
            ImageIcon btnluzPuertader = new ImageIcon(getClass().getResource("/Imagenes/puertaIzqLuz.jpg"));                   
            ImageIcon btnluzVentanader = new ImageIcon(getClass().getResource("/Imagenes/ventanaIzqLuz.png"));                   
            btn_luzizq.setIcon(btnluzder);
            puertaLuzizq.setIcon(btnluzPuertader);
            ventanaizq.setIcon(btnluzVentanader);
            banderaLuzIz = 1;
        } else if (banderaLuzIz == 1) { //APAGAR
            //ImageIcon btnverdeiz = new ImageIcon(getClass().getResource("/Imagenes/btnVerdeIz"));
            btn_luzizq.setIcon(null);
            puertaLuzizq.setIcon(null);
            ventanaizq.setIcon(null);
            banderaLuzIz = 0;
        }
    }//GEN-LAST:event_btn_luzizqMouseClicked

    private void btn_luzderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_luzderMouseClicked

        if (banderaLuzDer == 0) { //ENCENDER
            ImageIcon btnluzder = new ImageIcon(getClass().getResource("/Imagenes/luzbtnDer.jpg"));
            ImageIcon btnluzPuertader = new ImageIcon(getClass().getResource("/Imagenes/puertaDerLuzeEn.jpg"));                   
            ImageIcon btnluzVentanader = new ImageIcon(getClass().getResource("/Imagenes/venDerLuz.png"));                   
            btn_luzder.setIcon(btnluzder);
            puertaLuzder.setIcon(btnluzPuertader);
            ventanader.setIcon(btnluzVentanader);
            banderaLuzDer = 1;
        } else if (banderaLuzDer == 1) { //APAGAR
            //ImageIcon btnverdeiz = new ImageIcon(getClass().getResource("/Imagenes/btnVerdeIz"));
            btn_luzder.setIcon(null);
            puertaLuzder.setIcon(null);
            ventanader.setIcon(null);
            banderaLuzDer = 0;
        }

    }//GEN-LAST:event_btn_luzderMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    public void SetImage(JLabel labelname, String root) {

        ImageIcon imagen = new ImageIcon(root);
        Icon icon = new ImageIcon(imagen.getImage().getScaledInstance(labelname.getWidth(), labelname.getHeight(), Image.SCALE_DEFAULT));
        labelname.setIcon(icon);
        this.repaint();

    }

    public void llenarMisCuentasList() {

        //Array del tamaño de usuarios creados
        String[] user = new String[usuarios.size()];
        int i = 0;
        //Recorro mi arrayList de usuarios
        for (Usuario u : usuarios) {
            user[i] = u.getUsuario();
            i++;
        }

        //Lleno el comboBox
        JCB_LogIn.setModel(new DefaultComboBoxModel(user)); //
    }

    public JLabel getSetearCamara() {
        return setearCamara;
    }

    public void setSetearCamara(Icon ic) {
        this.setearCamara.setIcon(ic);
    }
    
    public String getNombreCam() {
        return locationCamara;
    }
    
    public void setNombreCam(String locCamara) {
        this.locationCamara = locCamara;
    }

    
    
    private HiloHora hHora;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JCB_LogIn;
    private javax.swing.JLabel JLbtnContinuarNoche;
    private javax.swing.JLabel JLbtnCrearUser;
    private javax.swing.JLabel JLbtnCrearUser1;
    private javax.swing.JLabel JLbtnNochePers1;
    private javax.swing.JLabel JLbtnNuevaPartida;
    private javax.swing.JLabel JLbtnNuevaPartidaAdmin;
    private javax.swing.JTextField Jtxtf_UsuarioAdd;
    private javax.swing.JLabel btnContinuarNocheAdmin;
    private javax.swing.JLabel btn_Cam1A;
    private javax.swing.JLabel btn_Cam1B;
    private javax.swing.JLabel btn_Cam1C;
    private javax.swing.JLabel btn_Cam2A;
    private javax.swing.JLabel btn_Cam2B;
    private javax.swing.JLabel btn_Cam3;
    private javax.swing.JLabel btn_Cam4A;
    private javax.swing.JLabel btn_Cam4B;
    private javax.swing.JLabel btn_Cam5;
    private javax.swing.JLabel btn_Cam6;
    private javax.swing.JLabel btn_Cam7;
    private javax.swing.JLabel btn_closecam;
    private javax.swing.JLabel btn_luzder;
    private javax.swing.JLabel btn_luzizq;
    private javax.swing.JLabel btn_opencam;
    private javax.swing.JLabel btn_puertader;
    private javax.swing.JLabel btn_puertaizq;
    private javax.swing.JPanel cam;
    private javax.swing.JPanel camCerrar;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbHora;
    private javax.swing.JLabel lbHoraCam;
    private javax.swing.JLabel lbMapa;
    private javax.swing.JLabel monitor;
    private javax.swing.JLabel monitor1;
    private javax.swing.JPanel oficina;
    private javax.swing.JPanel povcam;
    private javax.swing.JLabel puertaLuzder;
    private javax.swing.JLabel puertaLuzizq;
    private javax.swing.JLabel puertder;
    private javax.swing.JLabel puertizq;
    private javax.swing.JLabel setearCamara;
    private javax.swing.JLabel userLabel3;
    private javax.swing.JLabel userLabel4;
    private javax.swing.JDialog vCrearUsuario;
    private javax.swing.JDialog vMenuJuego;
    private javax.swing.JDialog vMenuJuegoAdmin;
    private javax.swing.JFrame vOficina;
    private javax.swing.JLabel ventanader;
    private javax.swing.JLabel ventanaizq;
    // End of variables declaration//GEN-END:variables
}
