/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectofnaf_carmencastillo;

import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.TimerTask;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author casti
 */
public class Main extends javax.swing.JFrame implements Runnable {

    //private ArrayList<Usuario> usuarios;
    private boolean noche1Admin = true;
    private boolean noche2Admin = false;
    private boolean noche3Admin = false;
    private boolean noche4Admin = false;
    private boolean CustnocheAdmin = false;

    private int banderaPuertaIz = 0;
    private int banderaPuertaDer = 0;
    private int banderaLuzDer = 0;
    private int banderaLuzIz = 0;
    private int banderaCamara = 0;
    private int contVecesCam = 0; //CONTAR CUANTAS VECES ENTRA O SALE
    private int contVecesCamClose = 0; //CONTAR CUANTAS VECES ENTRA O SALE
    private Thread Ref;
    //1 camara cerrada / 0 camara abierta
    //banderaluz 1 encendida / 0 apagada
    //banderaluzDer 1 encendida / 0 apagada
    //banderaPuerta 1 cerrada / 0 abierta
    //banderaPuertaDer 1 cerrada / 0 abierta
    public String locationCamara = "stage";

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(true);
        llenarMisCuentasList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vCrearUsuario = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        Jtxtf_UsuarioAdd = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        CrearUser = new javax.swing.JLabel();
        userLabel4 = new javax.swing.JLabel();
        userLabel5 = new javax.swing.JLabel();
        userLabel6 = new javax.swing.JLabel();
        chbx_diff = new javax.swing.JCheckBox();
        vMenuJuegoJugador = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        PonerPorCualNocheVa = new javax.swing.JLabel();
        btnContinuarNoche = new javax.swing.JLabel();
        JLbtnNochePers2 = new javax.swing.JLabel();
        btnNuevaPartida = new javax.swing.JLabel();
        koskd = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        vMenuJuegoAdmin = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        btnContinuarNocheAdmin1 = new javax.swing.JLabel();
        JLbtnNochePers1 = new javax.swing.JLabel();
        btnContinuarNocheAdmin = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        vOficina = new javax.swing.JFrame();
        oficina = new javax.swing.JPanel();
        lbCualNocheEs = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        BateriaRestante = new javax.swing.JLabel();
        UsoBateria = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbHora = new javax.swing.JLabel();
        btn_luzder = new javax.swing.JLabel();
        ventanader = new javax.swing.JLabel();
        ventanaizq = new javax.swing.JLabel();
        btn_luzizq = new javax.swing.JLabel();
        btn_puertader = new javax.swing.JLabel();
        btn_puertaizq = new javax.swing.JLabel();
        btn_opencam = new javax.swing.JLabel();
        puertizq = new javax.swing.JLabel();
        puertaLuzizq = new javax.swing.JLabel();
        puertder = new javax.swing.JLabel();
        puertaLuzder = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cam = new javax.swing.JPanel();
        monitor = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        camCerrar = new javax.swing.JPanel();
        monitor1 = new javax.swing.JLabel();
        fondo1 = new javax.swing.JLabel();
        povcam = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        BateriaRestanteCam = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        UsoBateriaCam = new javax.swing.JLabel();
        lbHoraCam = new javax.swing.JLabel();
        btn_Cam1A = new javax.swing.JLabel();
        btn_Cam1B = new javax.swing.JLabel();
        btn_Cam1C = new javax.swing.JLabel();
        btn_Cam2A = new javax.swing.JLabel();
        btn_Cam2B = new javax.swing.JLabel();
        btn_Cam3 = new javax.swing.JLabel();
        btn_Cam4A = new javax.swing.JLabel();
        btn_Cam4B = new javax.swing.JLabel();
        btn_Cam5 = new javax.swing.JLabel();
        btn_Cam6 = new javax.swing.JLabel();
        btn_Cam7 = new javax.swing.JLabel();
        btn_closecam = new javax.swing.JLabel();
        lbMapa = new javax.swing.JLabel();
        setearCamara = new javax.swing.JLabel();
        jumpscareBonnie = new javax.swing.JPanel();
        jsBon = new javax.swing.JLabel();
        jumpscareChica = new javax.swing.JPanel();
        jsChica = new javax.swing.JLabel();
        jumpscareFreddyNormal = new javax.swing.JPanel();
        jsFredN = new javax.swing.JLabel();
        jumpscareFreddysinLuz = new javax.swing.JPanel();
        jsFred = new javax.swing.JLabel();
        jumpscareFoxy = new javax.swing.JPanel();
        jsFox = new javax.swing.JLabel();
        jumpscareFredNormal = new javax.swing.JPanel();
        jsFreddyN = new javax.swing.JLabel();
        jumpscareGF = new javax.swing.JPanel();
        jsGF = new javax.swing.JLabel();
        BadEnding = new javax.swing.JPanel();
        bade = new javax.swing.JLabel();
        GoodEnding = new javax.swing.JPanel();
        goode = new javax.swing.JLabel();
        PantallaNegra = new javax.swing.JPanel();
        pantallan = new javax.swing.JLabel();
        GameOver = new javax.swing.JPanel();
        GO = new javax.swing.JLabel();
        Win5a6 = new javax.swing.JPanel();
        cinaseis = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        JCB_LogIn = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JLbtnCrearUser = new javax.swing.JLabel();
        EntrarComoAdmin = new javax.swing.JLabel();
        LogIn = new javax.swing.JLabel();

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/helpmi.gif"))); // NOI18N
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 70, 510, 500));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        Jtxtf_UsuarioAdd.setBackground(new java.awt.Color(0, 0, 0));
        Jtxtf_UsuarioAdd.setFont(new java.awt.Font("Five Fonts at Freddy's", 0, 24)); // NOI18N
        Jtxtf_UsuarioAdd.setForeground(new java.awt.Color(255, 255, 255));
        Jtxtf_UsuarioAdd.setBorder(null);
        Jtxtf_UsuarioAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtxtf_UsuarioAddActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));

        CrearUser.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        CrearUser.setForeground(new java.awt.Color(255, 255, 255));
        CrearUser.setText("Crear");
        CrearUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearUserMouseClicked(evt);
            }
        });

        userLabel4.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        userLabel4.setForeground(new java.awt.Color(255, 255, 255));
        userLabel4.setText("DIFICULTAD");

        userLabel5.setFont(new java.awt.Font("Roboto Light", 1, 40)); // NOI18N
        userLabel5.setForeground(new java.awt.Color(255, 255, 255));
        userLabel5.setText("CREAR USUARIO");

        userLabel6.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        userLabel6.setForeground(new java.awt.Color(255, 255, 255));
        userLabel6.setText("NOMBRE DE USUARIO");

        chbx_diff.setFont(new java.awt.Font("Five Fonts at Freddy's", 0, 18)); // NOI18N
        chbx_diff.setForeground(new java.awt.Color(255, 255, 255));
        chbx_diff.setText("    Seleccione para poner su dificultad en EASY");
        chbx_diff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbx_diffActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chbx_diff, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                    .addComponent(userLabel5)
                    .addComponent(userLabel6)
                    .addComponent(userLabel4)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(CrearUser, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Jtxtf_UsuarioAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                        .addComponent(jSeparator1)))
                .addContainerGap(700, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(userLabel5)
                .addGap(59, 59, 59)
                .addComponent(userLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Jtxtf_UsuarioAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(userLabel4)
                .addGap(18, 18, 18)
                .addComponent(chbx_diff, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(CrearUser)
                .addGap(115, 115, 115))
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1460, 650));

        javax.swing.GroupLayout vCrearUsuarioLayout = new javax.swing.GroupLayout(vCrearUsuario.getContentPane());
        vCrearUsuario.getContentPane().setLayout(vCrearUsuarioLayout);
        vCrearUsuarioLayout.setHorizontalGroup(
            vCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        vCrearUsuarioLayout.setVerticalGroup(
            vCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PonerPorCualNocheVa.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        PonerPorCualNocheVa.setForeground(new java.awt.Color(255, 255, 255));
        jPanel6.add(PonerPorCualNocheVa, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 60, 30));

        btnContinuarNoche.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        btnContinuarNoche.setForeground(new java.awt.Color(255, 255, 255));
        btnContinuarNoche.setText("Continuar Noche");
        btnContinuarNoche.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnContinuarNocheMouseClicked(evt);
            }
        });
        jPanel6.add(btnContinuarNoche, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 330, 40));

        JLbtnNochePers2.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        JLbtnNochePers2.setForeground(new java.awt.Color(255, 255, 255));
        JLbtnNochePers2.setText("Noche Personalizada");
        jPanel6.add(JLbtnNochePers2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, 390, 40));

        btnNuevaPartida.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        btnNuevaPartida.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevaPartida.setText("Nueva Partida");
        jPanel6.add(btnNuevaPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 260, 40));

        koskd.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        koskd.setForeground(new java.awt.Color(255, 255, 255));
        koskd.setText("Night");
        jPanel6.add(koskd, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 60, 30));

        jLabel20.setFont(new java.awt.Font("Verdana", 0, 45)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Five");
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 190, 50));

        jLabel21.setFont(new java.awt.Font("Verdana", 0, 45)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Nights");
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 240, 70));

        jLabel22.setFont(new java.awt.Font("Verdana", 0, 45)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("at");
        jPanel6.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 160, 50));

        jLabel23.setFont(new java.awt.Font("Verdana", 0, 45)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Freddy´s");
        jPanel6.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 280, 60));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menus.gif"))); // NOI18N
        jPanel6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1460, 650));

        javax.swing.GroupLayout vMenuJuegoJugadorLayout = new javax.swing.GroupLayout(vMenuJuegoJugador.getContentPane());
        vMenuJuegoJugador.getContentPane().setLayout(vMenuJuegoJugadorLayout);
        vMenuJuegoJugadorLayout.setHorizontalGroup(
            vMenuJuegoJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        vMenuJuegoJugadorLayout.setVerticalGroup(
            vMenuJuegoJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnContinuarNocheAdmin1.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        btnContinuarNocheAdmin1.setForeground(new java.awt.Color(255, 255, 255));
        btnContinuarNocheAdmin1.setText("Continuar Noche");
        jPanel4.add(btnContinuarNocheAdmin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 330, 40));

        JLbtnNochePers1.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        JLbtnNochePers1.setForeground(new java.awt.Color(255, 255, 255));
        JLbtnNochePers1.setText("Noche Personalizada");
        jPanel4.add(JLbtnNochePers1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, 390, 40));

        btnContinuarNocheAdmin.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        btnContinuarNocheAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnContinuarNocheAdmin.setText("Continuar Noche");
        jPanel4.add(btnContinuarNocheAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 330, 40));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 45)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Five");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 190, 50));

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 45)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nights");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 240, 70));

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 45)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("at");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 160, 50));

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 45)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Freddy´s");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 280, 60));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menus.gif"))); // NOI18N
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1460, 650));

        javax.swing.GroupLayout vMenuJuegoAdminLayout = new javax.swing.GroupLayout(vMenuJuegoAdmin.getContentPane());
        vMenuJuegoAdmin.getContentPane().setLayout(vMenuJuegoAdminLayout);
        vMenuJuegoAdminLayout.setHorizontalGroup(
            vMenuJuegoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        vMenuJuegoAdminLayout.setVerticalGroup(
            vMenuJuegoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        vOficina.setMinimumSize(new java.awt.Dimension(1463, 650));
        vOficina.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        oficina.setBackground(new java.awt.Color(0, 0, 0));
        oficina.setMinimumSize(new java.awt.Dimension(1463, 650));
        oficina.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbCualNocheEs.setBackground(new java.awt.Color(255, 255, 255));
        lbCualNocheEs.setFont(new java.awt.Font("Five Fonts at Freddy's", 0, 18)); // NOI18N
        lbCualNocheEs.setForeground(new java.awt.Color(255, 255, 255));
        oficina.add(lbCualNocheEs, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 70, 30, 40));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Five Fonts at Freddy's", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Night");
        oficina.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 70, 60, 40));

        BateriaRestante.setBackground(new java.awt.Color(255, 255, 255));
        BateriaRestante.setFont(new java.awt.Font("Five Fonts at Freddy's", 0, 18)); // NOI18N
        BateriaRestante.setForeground(new java.awt.Color(255, 255, 255));
        oficina.add(BateriaRestante, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, 130, 40));

        UsoBateria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/0bat.jpeg"))); // NOI18N
        oficina.add(UsoBateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 580, 110, 40));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Five Fonts at Freddy's", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Power Left:");
        oficina.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 130, 40));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Five Fonts at Freddy's", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Usage:");
        oficina.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, 80, 40));

        lbHora.setBackground(new java.awt.Color(255, 255, 255));
        lbHora.setFont(new java.awt.Font("Five Fonts at Freddy's", 0, 24)); // NOI18N
        lbHora.setForeground(new java.awt.Color(255, 255, 255));
        lbHora.setText("12 AM");
        oficina.add(lbHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 10, 80, 60));

        btn_luzder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_luzderMouseClicked(evt);
            }
        });
        oficina.add(btn_luzder, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 330, 50, 70));
        oficina.add(ventanader, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 70, 110, 360));
        oficina.add(ventanaizq, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 110, 360));

        btn_luzizq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_luzizqMouseClicked(evt);
            }
        });
        oficina.add(btn_luzizq, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 50, 70));

        btn_puertader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_puertaderMouseClicked(evt);
            }
        });
        oficina.add(btn_puertader, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 240, 60, 70));

        btn_puertaizq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_puertaizqMouseClicked(evt);
            }
        });
        oficina.add(btn_puertaizq, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 50, 70));

        btn_opencam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/barra1.jpeg"))); // NOI18N
        btn_opencam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_opencamMouseEntered(evt);
            }
        });
        oficina.add(btn_opencam, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 600, 520, 40));
        oficina.add(puertizq, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 230, 650));
        oficina.add(puertaLuzizq, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 230, 650));
        oficina.add(puertder, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 0, 200, 650));
        oficina.add(puertaLuzder, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 0, 200, 650));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ofi.jpg"))); // NOI18N
        oficina.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1460, 650));

        vOficina.getContentPane().add(oficina, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        cam.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        monitor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/monitorAbfinal.gif"))); // NOI18N
        monitor.setPreferredSize(new java.awt.Dimension(1463, 650));
        cam.add(monitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1460, 650));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ofi.jpg"))); // NOI18N
        cam.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        vOficina.getContentPane().add(cam, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, -4, 1460, 650));

        camCerrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        monitor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/monitorcFinal.gif"))); // NOI18N
        camCerrar.add(monitor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1460, 650));

        fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ofi.jpg"))); // NOI18N
        camCerrar.add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        vOficina.getContentPane().add(camCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, -4, 1460, 650));

        povcam.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Five Fonts at Freddy's", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Power Left:");
        povcam.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 130, 40));

        BateriaRestanteCam.setBackground(new java.awt.Color(255, 255, 255));
        BateriaRestanteCam.setFont(new java.awt.Font("Five Fonts at Freddy's", 0, 18)); // NOI18N
        BateriaRestanteCam.setForeground(new java.awt.Color(255, 255, 255));
        povcam.add(BateriaRestanteCam, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, 130, 40));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Five Fonts at Freddy's", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Usage:");
        povcam.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, 80, 40));

        UsoBateriaCam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/0bat.jpeg"))); // NOI18N
        povcam.add(UsoBateriaCam, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 580, 110, 40));

        lbHoraCam.setBackground(new java.awt.Color(255, 255, 255));
        lbHoraCam.setFont(new java.awt.Font("Five Fonts at Freddy's", 0, 24)); // NOI18N
        lbHoraCam.setForeground(new java.awt.Color(255, 255, 255));
        lbHoraCam.setText("12 AM");
        povcam.add(lbHoraCam, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 10, 80, 60));

        btn_Cam1A.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Cam1AMouseClicked(evt);
            }
        });
        povcam.add(btn_Cam1A, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 290, 60, 40));

        btn_Cam1B.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Cam1BMouseClicked(evt);
            }
        });
        povcam.add(btn_Cam1B, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 340, 60, 40));

        btn_Cam1C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Cam1CMouseClicked(evt);
            }
        });
        povcam.add(btn_Cam1C, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 420, 60, 40));

        btn_Cam2A.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Cam2AMouseClicked(evt);
            }
        });
        povcam.add(btn_Cam2A, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 540, 50, 30));

        btn_Cam2B.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Cam2BMouseClicked(evt);
            }
        });
        povcam.add(btn_Cam2B, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 580, 50, 30));

        btn_Cam3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Cam3MouseClicked(evt);
            }
        });
        povcam.add(btn_Cam3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 520, 60, 40));

        btn_Cam4A.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Cam4AMouseClicked(evt);
            }
        });
        povcam.add(btn_Cam4A, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 540, 50, 30));

        btn_Cam4B.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Cam4BMouseClicked(evt);
            }
        });
        povcam.add(btn_Cam4B, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 580, 50, 30));

        btn_Cam5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Cam5MouseClicked(evt);
            }
        });
        povcam.add(btn_Cam5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 370, 60, 40));

        btn_Cam6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Cam6MouseClicked(evt);
            }
        });
        povcam.add(btn_Cam6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 500, 60, 40));

        btn_Cam7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Cam7MouseClicked(evt);
            }
        });
        povcam.add(btn_Cam7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 370, 60, 40));

        btn_closecam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/barra1.jpeg"))); // NOI18N
        btn_closecam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_closecamMouseEntered(evt);
            }
        });
        povcam.add(btn_closecam, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 600, 520, 40));

        lbMapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mapap.png"))); // NOI18N
        povcam.add(lbMapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 290, 410, 340));

        setearCamara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/showstage_todos.jpg"))); // NOI18N
        povcam.add(setearCamara, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 650));

        vOficina.getContentPane().add(povcam, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, -4, 1470, 650));

        jsBon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/jsBonnie.gif"))); // NOI18N

        javax.swing.GroupLayout jumpscareBonnieLayout = new javax.swing.GroupLayout(jumpscareBonnie);
        jumpscareBonnie.setLayout(jumpscareBonnieLayout);
        jumpscareBonnieLayout.setHorizontalGroup(
            jumpscareBonnieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsBon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jumpscareBonnieLayout.setVerticalGroup(
            jumpscareBonnieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsBon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        vOficina.getContentPane().add(jumpscareBonnie, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jsChica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/jsChica.gif"))); // NOI18N

        javax.swing.GroupLayout jumpscareChicaLayout = new javax.swing.GroupLayout(jumpscareChica);
        jumpscareChica.setLayout(jumpscareChicaLayout);
        jumpscareChicaLayout.setHorizontalGroup(
            jumpscareChicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsChica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jumpscareChicaLayout.setVerticalGroup(
            jumpscareChicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsChica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        vOficina.getContentPane().add(jumpscareChica, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jsFredN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/jsFreddy2.gif"))); // NOI18N

        javax.swing.GroupLayout jumpscareFreddyNormalLayout = new javax.swing.GroupLayout(jumpscareFreddyNormal);
        jumpscareFreddyNormal.setLayout(jumpscareFreddyNormalLayout);
        jumpscareFreddyNormalLayout.setHorizontalGroup(
            jumpscareFreddyNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsFredN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jumpscareFreddyNormalLayout.setVerticalGroup(
            jumpscareFreddyNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsFredN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        vOficina.getContentPane().add(jumpscareFreddyNormal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jsFred.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/jsFreddy.gif"))); // NOI18N

        javax.swing.GroupLayout jumpscareFreddysinLuzLayout = new javax.swing.GroupLayout(jumpscareFreddysinLuz);
        jumpscareFreddysinLuz.setLayout(jumpscareFreddysinLuzLayout);
        jumpscareFreddysinLuzLayout.setHorizontalGroup(
            jumpscareFreddysinLuzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsFred, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jumpscareFreddysinLuzLayout.setVerticalGroup(
            jumpscareFreddysinLuzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsFred, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        vOficina.getContentPane().add(jumpscareFreddysinLuz, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jsFox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/jsFoxy.gif"))); // NOI18N

        javax.swing.GroupLayout jumpscareFoxyLayout = new javax.swing.GroupLayout(jumpscareFoxy);
        jumpscareFoxy.setLayout(jumpscareFoxyLayout);
        jumpscareFoxyLayout.setHorizontalGroup(
            jumpscareFoxyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsFox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jumpscareFoxyLayout.setVerticalGroup(
            jumpscareFoxyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsFox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        vOficina.getContentPane().add(jumpscareFoxy, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout jumpscareFredNormalLayout = new javax.swing.GroupLayout(jumpscareFredNormal);
        jumpscareFredNormal.setLayout(jumpscareFredNormalLayout);
        jumpscareFredNormalLayout.setHorizontalGroup(
            jumpscareFredNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsFreddyN, javax.swing.GroupLayout.DEFAULT_SIZE, 1463, Short.MAX_VALUE)
        );
        jumpscareFredNormalLayout.setVerticalGroup(
            jumpscareFredNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsFreddyN, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        vOficina.getContentPane().add(jumpscareFredNormal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout jumpscareGFLayout = new javax.swing.GroupLayout(jumpscareGF);
        jumpscareGF.setLayout(jumpscareGFLayout);
        jumpscareGFLayout.setHorizontalGroup(
            jumpscareGFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsGF, javax.swing.GroupLayout.DEFAULT_SIZE, 1463, Short.MAX_VALUE)
        );
        jumpscareGFLayout.setVerticalGroup(
            jumpscareGFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsGF, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        vOficina.getContentPane().add(jumpscareGF, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        bade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/badDSPCN.jpg"))); // NOI18N

        javax.swing.GroupLayout BadEndingLayout = new javax.swing.GroupLayout(BadEnding);
        BadEnding.setLayout(BadEndingLayout);
        BadEndingLayout.setHorizontalGroup(
            BadEndingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BadEndingLayout.setVerticalGroup(
            BadEndingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        vOficina.getContentPane().add(BadEnding, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        goode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/goodDSP5.jpg"))); // NOI18N

        javax.swing.GroupLayout GoodEndingLayout = new javax.swing.GroupLayout(GoodEnding);
        GoodEnding.setLayout(GoodEndingLayout);
        GoodEndingLayout.setHorizontalGroup(
            GoodEndingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(goode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        GoodEndingLayout.setVerticalGroup(
            GoodEndingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(goode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        vOficina.getContentPane().add(GoodEnding, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout PantallaNegraLayout = new javax.swing.GroupLayout(PantallaNegra);
        PantallaNegra.setLayout(PantallaNegraLayout);
        PantallaNegraLayout.setHorizontalGroup(
            PantallaNegraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pantallan, javax.swing.GroupLayout.DEFAULT_SIZE, 1463, Short.MAX_VALUE)
        );
        PantallaNegraLayout.setVerticalGroup(
            PantallaNegraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pantallan, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        vOficina.getContentPane().add(PantallaNegra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        GO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gameOver.jpg"))); // NOI18N

        javax.swing.GroupLayout GameOverLayout = new javax.swing.GroupLayout(GameOver);
        GameOver.setLayout(GameOverLayout);
        GameOverLayout.setHorizontalGroup(
            GameOverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        GameOverLayout.setVerticalGroup(
            GameOverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        vOficina.getContentPane().add(GameOver, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        cinaseis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/5a6.gif"))); // NOI18N

        javax.swing.GroupLayout Win5a6Layout = new javax.swing.GroupLayout(Win5a6);
        Win5a6.setLayout(Win5a6Layout);
        Win5a6Layout.setHorizontalGroup(
            Win5a6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cinaseis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Win5a6Layout.setVerticalGroup(
            Win5a6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cinaseis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        vOficina.getContentPane().add(Win5a6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        JCB_LogIn.setBackground(new java.awt.Color(0, 0, 0));
        JCB_LogIn.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setText("Ingresar con Usuario");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/helpyYA.gif"))); // NOI18N

        JLbtnCrearUser.setFont(new java.awt.Font("Verdana", 0, 30)); // NOI18N
        JLbtnCrearUser.setForeground(new java.awt.Color(255, 255, 255));
        JLbtnCrearUser.setText("Crear Usuario");
        JLbtnCrearUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLbtnCrearUserMouseClicked(evt);
            }
        });

        EntrarComoAdmin.setFont(new java.awt.Font("Verdana", 0, 30)); // NOI18N
        EntrarComoAdmin.setForeground(new java.awt.Color(255, 255, 255));
        EntrarComoAdmin.setText("Entrar como Administrador");
        EntrarComoAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EntrarComoAdminMouseClicked(evt);
            }
        });

        LogIn.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        LogIn.setForeground(new java.awt.Color(255, 255, 255));
        LogIn.setText("Log-In");
        LogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogInMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EntrarComoAdmin)
                            .addComponent(JLbtnCrearUser, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JCB_LogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(144, 144, 144))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(LogIn)
                        .addGap(121, 121, 121)))
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(EntrarComoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(JLbtnCrearUser, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JCB_LogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JLbtnCrearUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLbtnCrearUserMouseClicked
        this.setVisible(false);
        vCrearUsuario.pack();
        vCrearUsuario.setLocationRelativeTo(null);
        vCrearUsuario.setVisible(true);


    }//GEN-LAST:event_JLbtnCrearUserMouseClicked

    private void Jtxtf_UsuarioAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtxtf_UsuarioAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtxtf_UsuarioAddActionPerformed

    private void EntrarComoAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntrarComoAdminMouseClicked

        this.setVisible(false);
        vMenuJuegoAdmin.pack();
        vMenuJuegoAdmin.setLocationRelativeTo(null);
        vMenuJuegoAdmin.setVisible(true);

    }//GEN-LAST:event_EntrarComoAdminMouseClicked

    private void btn_opencamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_opencamMouseEntered
        //hiloMon.start();
        contVecesCam++;
        contVecesCamClose = 0;
        banderaCamara = 1; //
        if (contVecesCam == 1) {
            barraBat++;
            //DrenajeBat = DrenajeBat-0.2;
        }
        HiloCamAnimation hCam = new HiloCamAnimation(cam, oficina, povcam);
        hCam.start();

    }//GEN-LAST:event_btn_opencamMouseEntered

    private void btn_puertaizqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_puertaizqMouseClicked
        //int bandera = 0; //abierta
        //int bandera = 1 cerrada

        if (banderaPuertaIz == 0) { //CERRAR
            HiloCloseDoor hCD = new HiloCloseDoor(puertizq);
            ImageIcon btnverdeiz = new ImageIcon(getClass().getResource("/Imagenes/btnVerdeIz.jpg"));
            btn_puertaizq.setIcon(btnverdeiz);
            hCD.start();
            banderaPuertaIz = 1;
            //DrenajeBat = DrenajeBat-0.2;
            barraBat++;
        } else if (banderaPuertaIz == 1) {
            HiloOpenDoor hOD = new HiloOpenDoor(puertizq);
            //ImageIcon btnverdeiz = new ImageIcon(getClass().getResource("/Imagenes/btnVerdeIz"));
            btn_puertaizq.setIcon(null);
            hOD.start();
            barraBat--;
            banderaPuertaIz = 0;
        }


    }//GEN-LAST:event_btn_puertaizqMouseClicked

    private void btn_puertaderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_puertaderMouseClicked
        //int bandera = 0; //abierta
        //int bandera = 1 cerrada

        if (banderaPuertaDer == 0) { //CERRAR
            HiloCloseDoorDerecha hCD = new HiloCloseDoorDerecha(puertder);
            ImageIcon btnverdeiz = new ImageIcon(getClass().getResource("/Imagenes/btnVerdeDer.jpg"));
            btn_puertader.setIcon(btnverdeiz);
            hCD.start();
            banderaPuertaDer = 1;
            //DrenajeBat = DrenajeBat-0.2;
            barraBat++;
        } else if (banderaPuertaDer == 1) { //abrir
            HiloOpenDoorDerecha hOD = new HiloOpenDoorDerecha(puertder);
            //ImageIcon btnverdeiz = new ImageIcon(getClass().getResource("/Imagenes/btnVerdeIz"));
            btn_puertader.setIcon(null);
            hOD.start();
            barraBat--;
            banderaPuertaDer = 0;
        }
    }//GEN-LAST:event_btn_puertaderMouseClicked

    private void btn_closecamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closecamMouseEntered
        banderaCamara = 0;
        contVecesCamClose++;
        contVecesCam = 0;
        if (contVecesCamClose == 1) {
            barraBat--;
        }
        HiloCloseCam hCloseCam = new HiloCloseCam(camCerrar, oficina, povcam);
        hCloseCam.start();
    }//GEN-LAST:event_btn_closecamMouseEntered

    private void btn_Cam1AMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cam1AMouseClicked
        locationCamara = "stage";
        System.out.println(locationCamara);
    }//GEN-LAST:event_btn_Cam1AMouseClicked

    private void btn_Cam1BMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cam1BMouseClicked
        locationCamara = "dinning";
        //System.out.println(locationCamara);
    }//GEN-LAST:event_btn_Cam1BMouseClicked

    private void btn_Cam1CMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cam1CMouseClicked
        locationCamara = "pirateCove";
        //System.out.println(locationCamara);
    }//GEN-LAST:event_btn_Cam1CMouseClicked

    private void btn_Cam2AMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cam2AMouseClicked
        locationCamara = "wHall";
    }//GEN-LAST:event_btn_Cam2AMouseClicked

    private void btn_Cam2BMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cam2BMouseClicked
        locationCamara = "wHallCorner";
    }//GEN-LAST:event_btn_Cam2BMouseClicked

    private void btn_Cam3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cam3MouseClicked
        locationCamara = "supplyCloset";
    }//GEN-LAST:event_btn_Cam3MouseClicked

    private void btn_Cam4AMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cam4AMouseClicked
        locationCamara = "eHall";
    }//GEN-LAST:event_btn_Cam4AMouseClicked

    private void btn_Cam4BMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cam4BMouseClicked
        locationCamara = "eHallCorner";
    }//GEN-LAST:event_btn_Cam4BMouseClicked

    private void btn_Cam5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cam5MouseClicked
        locationCamara = "backstage";
    }//GEN-LAST:event_btn_Cam5MouseClicked

    private void btn_Cam6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cam6MouseClicked
        locationCamara = "kitchen"; //CAM DISABLE
    }//GEN-LAST:event_btn_Cam6MouseClicked

    private void btn_Cam7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cam7MouseClicked
        locationCamara = "restrooms";
    }//GEN-LAST:event_btn_Cam7MouseClicked

    private void btn_luzizqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_luzizqMouseClicked
        if (banderaLuzIz == 0) { //ENCENDER
            ImageIcon btnluzder = new ImageIcon(getClass().getResource("/Imagenes/luzbtnIzq.jpg"));
            ImageIcon btnluzPuertader = new ImageIcon(getClass().getResource("/Imagenes/puertaIzqLuz.jpg"));
            ImageIcon btnluzVentanader = new ImageIcon(getClass().getResource("/Imagenes/ventanaIzqLuz.png"));
            btn_luzizq.setIcon(btnluzder);
            puertaLuzizq.setIcon(btnluzPuertader);
            ventanaizq.setIcon(btnluzVentanader);
            banderaLuzIz = 1;
            //DrenajeBat = DrenajeBat-0.2;
            barraBat++;
        } else if (banderaLuzIz == 1) { //APAGAR
            //ImageIcon btnverdeiz = new ImageIcon(getClass().getResource("/Imagenes/btnVerdeIz"));
            btn_luzizq.setIcon(null);
            puertaLuzizq.setIcon(null);
            ventanaizq.setIcon(null);
            banderaLuzIz = 0;
            barraBat--;
        }
    }//GEN-LAST:event_btn_luzizqMouseClicked

    private void btn_luzderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_luzderMouseClicked

        if (banderaLuzDer == 0) { //ENCENDER
            ImageIcon btnluzder = new ImageIcon(getClass().getResource("/Imagenes/luzbtnDer.jpg"));
            ImageIcon btnluzPuertader = new ImageIcon(getClass().getResource("/Imagenes/puertaDerLuzeEn.jpg"));
            ImageIcon btnluzVentanader = new ImageIcon(getClass().getResource("/Imagenes/venDerLuz.png"));
            btn_luzder.setIcon(btnluzder);
            puertaLuzder.setIcon(btnluzPuertader);
            ventanader.setIcon(btnluzVentanader);
            banderaLuzDer = 1;
            //DrenajeBat = DrenajeBat-0.2;
            barraBat++;
        } else if (banderaLuzDer == 1) { //APAGAR
            //ImageIcon btnverdeiz = new ImageIcon(getClass().getResource("/Imagenes/btnVerdeIz"));
            btn_luzder.setIcon(null);
            puertaLuzder.setIcon(null);
            ventanader.setIcon(null);
            banderaLuzDer = 0;
            barraBat--;
        }

    }//GEN-LAST:event_btn_luzderMouseClicked

    private void CrearUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearUserMouseClicked

        boolean ValidUser = true;

        AdminUser aUser = new AdminUser("./Usuarios.fok");
        aUser.cargarArchivo();

        String user = Jtxtf_UsuarioAdd.getText();
        boolean easy;

        if (chbx_diff.isSelected()) {
            easy = true;
        } else {
            easy = false;
        }

        for (Usuario usuario : aUser.getListaUsuarios()) {
            if (usuario.getUsuario().equals(user)) {
                JOptionPane.showMessageDialog(vCrearUsuario, "Nombre de usuario ya existente.");
                ValidUser = false;
            }
        }
        if (Jtxtf_UsuarioAdd.getText().equals("")) {
            JOptionPane.showMessageDialog(vCrearUsuario, "Cree su usuario.");
            ValidUser = false;
        }

        if (ValidUser) {
            Usuario u = new Usuario(user, easy, true, false, false, false, false, 1);
            aUser.setUsuario(u);
            aUser.escribirArchivo();
            Jtxtf_UsuarioAdd.setText("");
            vCrearUsuario.pack();
            vCrearUsuario.setLocationRelativeTo(null);
            vCrearUsuario.setVisible(false);
            this.setVisible(true);
            llenarMisCuentasList();
        }


    }//GEN-LAST:event_CrearUserMouseClicked

    private void chbx_diffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbx_diffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbx_diffActionPerformed

    private void LogInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogInMouseClicked
        this.setVisible(true);
        vMenuJuegoJugador.pack();
        vMenuJuegoJugador.setLocationRelativeTo(null);
        vMenuJuegoJugador.setVisible(true);
        
        AdminUser aUser = new AdminUser("./Usuarios.fok");
        aUser.cargarArchivo();
        
        for (Usuario usuario : aUser.getListaUsuarios()) {
            if (JCB_LogIn.getSelectedItem().equals(usuario.getUsuario())) {
                if (usuario.getNoche() == 1) {
                    PonerPorCualNocheVa.setText("1");
                } else if (usuario.getNoche() == 2){
                    PonerPorCualNocheVa.setText("2");
                } else if (usuario.getNoche() == 3){
                    PonerPorCualNocheVa.setText("3");
                } else if (usuario.getNoche() == 4){
                    PonerPorCualNocheVa.setText("4");
                } 
                
            }
        }
    }//GEN-LAST:event_LogInMouseClicked

    private void btnContinuarNocheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContinuarNocheMouseClicked
        
        
        
    }//GEN-LAST:event_btnContinuarNocheMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    public void SetImage(JLabel labelname, String root) {

        ImageIcon imagen = new ImageIcon(root);
        Icon icon = new ImageIcon(imagen.getImage().getScaledInstance(labelname.getWidth(), labelname.getHeight(), Image.SCALE_DEFAULT));
        labelname.setIcon(icon);
        this.repaint();

    }

    public void Bateria() {

        if (barraBat == 0) {

        } else if (barraBat == 1) {
            DrenajeBat = DrenajeBat - 0.2;
        } else if (barraBat == 2) {
            DrenajeBat = DrenajeBat - 0.4;
        } else if (barraBat == 3) {
            DrenajeBat = DrenajeBat - 0.6;
        } else if (barraBat == 4) {
            DrenajeBat = DrenajeBat - 0.8;
        } else if (barraBat == 5) {
            DrenajeBat = DrenajeBat - 1;
        }

    }
    
    public boolean SacarModo(){
        boolean Modo = true;
        
        AdminUser aUser = new AdminUser("./Usuarios.fok");
        aUser.cargarArchivo();
        
        for (Usuario u : aUser.getListaUsuarios()) {
            if (JCB_LogIn.getSelectedItem().equals(u.getUsuario())) {
                Modo = u.isEasy();
            }
        }
        return Modo;
    }
    
    public boolean BuscarNoche1(){
        
        boolean Noche = true;
        
        AdminUser aUser = new AdminUser("./Usuarios.fok");
        aUser.cargarArchivo();
        
        for (Usuario u : aUser.getListaUsuarios()) {
            if (JCB_LogIn.getSelectedItem().equals(u.getUsuario())) {
                Noche = u.isNoche1();
            }
        }
        return Noche;        
    }
    
    public boolean BuscarNoche2(){
        
        boolean Noche2 = true;
        
        AdminUser aUser = new AdminUser("./Usuarios.fok");
        aUser.cargarArchivo();
        
        for (Usuario u : aUser.getListaUsuarios()) {
            if (JCB_LogIn.getSelectedItem().equals(u.getUsuario())) {
                Noche2 = u.isNoche2();
            }
        }
        return Noche2;        
    }
    
    public boolean BuscarNoche3(){
        
        boolean Noche3 = true;
        
        AdminUser aUser = new AdminUser("./Usuarios.fok");
        aUser.cargarArchivo();
        
        for (Usuario u : aUser.getListaUsuarios()) {
            if (JCB_LogIn.getSelectedItem().equals(u.getUsuario())) {
                Noche3 = u.isNoche3();
            }
        }
        return Noche3;        
    }

    public void llenarMisCuentasList() {

        JCB_LogIn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{}));
        AdminUser aCirc = new AdminUser("./Usuarios.fok");
        aCirc.cargarArchivo();
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) JCB_LogIn.getModel();
        for (Usuario user : aCirc.getListaUsuarios()) {
            modelo.addElement(user.getUsuario());
        }

    }

    public JLabel getSetearCamara() {
        return setearCamara;
    }

    public void setSetearCamara(Icon ic) {
        this.setearCamara.setIcon(ic);
    }

    public String getNombreCam() {
        return locationCamara;
    }

    public void setNombreCam(String locCamara) {
        this.locationCamara = locCamara;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BadEnding;
    private javax.swing.JLabel BateriaRestante;
    private javax.swing.JLabel BateriaRestanteCam;
    private javax.swing.JLabel CrearUser;
    private javax.swing.JLabel EntrarComoAdmin;
    private javax.swing.JLabel GO;
    private javax.swing.JPanel GameOver;
    private javax.swing.JPanel GoodEnding;
    private javax.swing.JComboBox<String> JCB_LogIn;
    private javax.swing.JLabel JLbtnCrearUser;
    private javax.swing.JLabel JLbtnNochePers1;
    private javax.swing.JLabel JLbtnNochePers2;
    private javax.swing.JTextField Jtxtf_UsuarioAdd;
    private javax.swing.JLabel LogIn;
    private javax.swing.JPanel PantallaNegra;
    private javax.swing.JLabel PonerPorCualNocheVa;
    private javax.swing.JLabel UsoBateria;
    private javax.swing.JLabel UsoBateriaCam;
    private javax.swing.JPanel Win5a6;
    private javax.swing.JLabel bade;
    private javax.swing.JLabel btnContinuarNoche;
    private javax.swing.JLabel btnContinuarNocheAdmin;
    private javax.swing.JLabel btnContinuarNocheAdmin1;
    private javax.swing.JLabel btnNuevaPartida;
    private javax.swing.JLabel btn_Cam1A;
    private javax.swing.JLabel btn_Cam1B;
    private javax.swing.JLabel btn_Cam1C;
    private javax.swing.JLabel btn_Cam2A;
    private javax.swing.JLabel btn_Cam2B;
    private javax.swing.JLabel btn_Cam3;
    private javax.swing.JLabel btn_Cam4A;
    private javax.swing.JLabel btn_Cam4B;
    private javax.swing.JLabel btn_Cam5;
    private javax.swing.JLabel btn_Cam6;
    private javax.swing.JLabel btn_Cam7;
    private javax.swing.JLabel btn_closecam;
    private javax.swing.JLabel btn_luzder;
    private javax.swing.JLabel btn_luzizq;
    private javax.swing.JLabel btn_opencam;
    private javax.swing.JLabel btn_puertader;
    private javax.swing.JLabel btn_puertaizq;
    private javax.swing.JPanel cam;
    private javax.swing.JPanel camCerrar;
    private javax.swing.JCheckBox chbx_diff;
    private javax.swing.JLabel cinaseis;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondo1;
    private javax.swing.JLabel goode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jsBon;
    private javax.swing.JLabel jsChica;
    private javax.swing.JLabel jsFox;
    private javax.swing.JLabel jsFred;
    private javax.swing.JLabel jsFredN;
    private javax.swing.JLabel jsFreddyN;
    private javax.swing.JLabel jsGF;
    private javax.swing.JPanel jumpscareBonnie;
    private javax.swing.JPanel jumpscareChica;
    private javax.swing.JPanel jumpscareFoxy;
    private javax.swing.JPanel jumpscareFredNormal;
    private javax.swing.JPanel jumpscareFreddyNormal;
    private javax.swing.JPanel jumpscareFreddysinLuz;
    private javax.swing.JPanel jumpscareGF;
    private javax.swing.JLabel koskd;
    private javax.swing.JLabel lbCualNocheEs;
    private javax.swing.JLabel lbHora;
    private javax.swing.JLabel lbHoraCam;
    private javax.swing.JLabel lbMapa;
    private javax.swing.JLabel monitor;
    private javax.swing.JLabel monitor1;
    private javax.swing.JPanel oficina;
    private javax.swing.JLabel pantallan;
    private javax.swing.JPanel povcam;
    private javax.swing.JLabel puertaLuzder;
    private javax.swing.JLabel puertaLuzizq;
    private javax.swing.JLabel puertder;
    private javax.swing.JLabel puertizq;
    private javax.swing.JLabel setearCamara;
    private javax.swing.JLabel userLabel4;
    private javax.swing.JLabel userLabel5;
    private javax.swing.JLabel userLabel6;
    private javax.swing.JDialog vCrearUsuario;
    private javax.swing.JDialog vMenuJuegoAdmin;
    private javax.swing.JDialog vMenuJuegoJugador;
    private javax.swing.JFrame vOficina;
    private javax.swing.JLabel ventanader;
    private javax.swing.JLabel ventanaizq;
    // End of variables declaration//GEN-END:variables

    private int contador = 0;
    private int contador2 = 0;
    private boolean isAlive = true;
    private int barraBat = 0;
    private double DrenajeBat = 100;
    private int EnteroDrenajeBat = (int) DrenajeBat;
    private Bonnie bon = new Bonnie(15);
    private Chica chic = new Chica(15);

    @Override
    public void run() {
        
        
        while (isAlive) {
            contador2++;

            try {
                Thread.sleep(1);
            } catch (Exception e) {
            }
            
            if (rootPaneCheckingEnabled) {
                if (rootPaneCheckingEnabled) {
                    
                }
            }
            
            System.out.println("");
            System.out.println(contador2);
            //System.out.println(contador);
            System.out.println();
            if (contador2 == 10000) {
                bon.movimiento();
                chic.movimiento();
                //Bateria();
                contador2 = 0;
            }

            if (contador2 % 1000 == 0) {
                Bateria();
            }

            System.out.println("Bonnie pos: " + bon.getUbic());
            System.out.println();
            System.out.println("Chica pos: " + chic.getUbic());
            System.out.println();
            System.out.println("Bat " + barraBat);
            System.out.println("ENTERO RESTANTE " + EnteroDrenajeBat);
            System.out.println("RESTANTE " + DrenajeBat);

            EnteroDrenajeBat = (int) DrenajeBat;
            BateriaRestante.setText(" " + String.valueOf(EnteroDrenajeBat) + "%");
            BateriaRestanteCam.setText(" " + String.valueOf(EnteroDrenajeBat) + "%");
            if (locationCamara.equals("stage")) { // 1A
                if (bon.getUbic() == 0 && chic.getUbic() == 0) { //estan los tres
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/showstage_todos.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }
                if (bon.getUbic() != 0 && chic.getUbic() == 0) { //estan sin bonnie
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/SHSsinBonnie.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }
                if (bon.getUbic() == 0 && chic.getUbic() != 0) { //estan sin chica
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/SHSsinChica.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }
                if (bon.getUbic() != 0 && chic.getUbic() != 0) { //solo freddy
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/SHSSOLOFreddy.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }

            }

            if (locationCamara.equals("dinning")) { //1, 2 BONNIE Y CHICA //FREDDY SOLO 1 // bon 1 2 / chic 1 2 / fred 1 //1B

                if (bon.getUbic() != 1 && chic.getUbic() != 1 && chic.getUbic() != 2 && bon.getUbic() != 2) { //vacio
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/DinnerVacio.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }
                if (bon.getUbic() == 1 && chic.getUbic() != 1 && chic.getUbic() != 2 && bon.getUbic() != 2) { //bonnie 1
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/DinnerBonnie1.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }
                if (bon.getUbic() != 1 && chic.getUbic() != 1 && chic.getUbic() != 2 && bon.getUbic() == 2) { //bonnie 2
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/DinningBonnie2.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }
                if (bon.getUbic() != 1 && chic.getUbic() == 1 && chic.getUbic() != 2 && bon.getUbic() != 2) { //chica 1
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/DinnerChica1.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }
                if (bon.getUbic() != 1 && chic.getUbic() != 1 && chic.getUbic() == 2 && bon.getUbic() != 2) { //chica 2
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/DinnerChica2.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }
                if ((bon.getUbic() == 1 && chic.getUbic() == 1) || (chic.getUbic() == 2 && bon.getUbic() == 2)) { //si estan bonnie y chica
                    bon.setUbic(3);
                }
                if ((bon.getUbic() == 1 && chic.getUbic() == 2) || (chic.getUbic() == 1 && bon.getUbic() == 2)) { //si estan bonnie y 
                    bon.setUbic(3);
                }

            }

            if (locationCamara.equals("pirateCove")) { //FOXY 0 1 2 y si se fue // 1C
                ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/PirateC_0.jpg"));
                setearCamara.setIcon(showstage_todos);
            }

            if (locationCamara.equals("wHall")) { // gif fox 3 / bon 5 //2A

                if (bon.getUbic() != 5) { //VACIO
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/wHallVacio.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }
                if (bon.getUbic() == 5) { //BONNIE /tiene 7 posiciones creo
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/wHallBonnie.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }

            }

            if (locationCamara.equals("wHallCorner")) { //bon 7 // gf no se //2B

                if (bon.getUbic() != 7) { //VACIO
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/wHallCVacio.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }
                if (bon.getUbic() == 7) { //bonnie
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/wHallCBon.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }

            }

            if (locationCamara.equals("supplyCloset")) { // bon 6         //3

                if (bon.getUbic() != 6) { //VACIO
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/ClosetVacio.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }
                if (bon.getUbic() == 6) { //bonnie
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/ClosetBon.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }

            }

            if (locationCamara.equals("eHall")) { //chic 6 7 / fred 3 //4A

                if (chic.getUbic() != 6 && chic.getUbic() != 7) { //VACIO
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/eHallVacio.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }
                if (chic.getUbic() == 6 && chic.getUbic() != 7) { //CHICA
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/eHallChica6.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }
                if (chic.getUbic() != 6 && chic.getUbic() == 7) { //CHICA CERCA
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/eHallChica7.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }
            }

            if (locationCamara.equals("eHallCorner")) { //chic 8 / fred 4 //4B

                if (chic.getUbic() != 8) { //vacio
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/eHallCornerVacio.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }
                if (chic.getUbic() == 8) { //chica
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/eHallCornerChica.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }

            }

            if (locationCamara.equals("backstage")) { //bon 3 4            //5

                if (bon.getUbic() != 3 && bon.getUbic() != 4) { //vacio
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/backstVacio.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }
                if (bon.getUbic() == 3 && bon.getUbic() != 4) { //bonnie
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/backstBonnie1.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }
                if (bon.getUbic() != 3 && bon.getUbic() == 4) { //bonnie
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/backstBonnie2.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }

            }

            if (locationCamara.equals("kitchen")) { //chic 5            //6
                //camara desabilitada
                ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/static.gif"));
                setearCamara.setIcon(showstage_todos);

            }

            if (locationCamara.equals("restrooms")) { //chic 3 4 / fred 2     //7

                if (chic.getUbic() != 3 && chic.getUbic() != 4) { //VACIO
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/restroomVacio.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }
                if (chic.getUbic() == 3 && chic.getUbic() != 4) { //CHICA
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/restroomChica1.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }
                if (chic.getUbic() != 3 && chic.getUbic() == 4) { //CHICA CERCA
                    ImageIcon showstage_todos = new ImageIcon(getClass().getResource("/Imagenes/restroomChica2.jpg"));
                    setearCamara.setIcon(showstage_todos);
                }

            }

            if (banderaLuzDer == 1 && chic.getUbic() == 9) {
                ImageIcon btnluzVentanader = new ImageIcon(getClass().getResource("/Imagenes/venDerLuzChica2.png"));
                ventanader.setIcon(btnluzVentanader);
            }

            if (banderaLuzIz == 1 && bon.getUbic() == 8) {
                ImageIcon btnluzPuertader = new ImageIcon(getClass().getResource("/Imagenes/bonofiLuzEn.jpg"));
                puertaLuzizq.setIcon(btnluzPuertader);
            }

            if (bon.getUbic() == 9 && banderaPuertaIz == 0 && banderaCamara == 0) {
                HiloJumpscareB hJSBon = new HiloJumpscareB(jumpscareBonnie, this, vOficina, oficina);
                hJSBon.start();
                return;
            }

            if (chic.getUbic() == 10 && banderaPuertaDer == 0 && banderaCamara == 0) {
                HiloJSChica hJSChic = new HiloJSChica(jumpscareChica, this, vOficina, oficina);
                hJSChic.start();
                return;
            }

            if (chic.getUbic() == 9 && banderaPuertaDer == 1) {
                chic.setUbic(1);
            }

            if (bon.getUbic() == 8 && banderaPuertaIz == 1) {
                bon.setUbic(1);
            }

            if (barraBat == 0) {
                ImageIcon barraBateria = new ImageIcon(getClass().getResource("/Imagenes/0bat.jpeg"));
                UsoBateria.setIcon(barraBateria);
                UsoBateriaCam.setIcon(barraBateria);

            } else if (barraBat == 1) {
                ImageIcon barraBateria = new ImageIcon(getClass().getResource("/Imagenes/1bat.jpeg"));
                UsoBateria.setIcon(barraBateria);
                UsoBateriaCam.setIcon(barraBateria);

            } else if (barraBat == 2) {
                ImageIcon barraBateria = new ImageIcon(getClass().getResource("/Imagenes/2bat.jpeg"));
                UsoBateria.setIcon(barraBateria);
                UsoBateriaCam.setIcon(barraBateria);

            } else if (barraBat == 3) {
                ImageIcon barraBateria = new ImageIcon(getClass().getResource("/Imagenes/3bat.jpeg"));
                UsoBateria.setIcon(barraBateria);
                UsoBateriaCam.setIcon(barraBateria);

            } else if (barraBat == 4) {
                ImageIcon barraBateria = new ImageIcon(getClass().getResource("/Imagenes/4bat.jpeg"));
                UsoBateria.setIcon(barraBateria);
                UsoBateriaCam.setIcon(barraBateria);

            } else if (barraBat == 5) {
                ImageIcon barraBateria = new ImageIcon(getClass().getResource("/Imagenes/5bat.jpeg"));
                UsoBateria.setIcon(barraBateria);
                UsoBateriaCam.setIcon(barraBateria);

            }

            //NOCHE 2
            contador++;
            if (!Ref.isAlive()) {
                HiloGane hGane = new HiloGane(Win5a6, this, vOficina, oficina);
                hGane.start();
                isAlive = false;

                //Ref.stop();
                System.out.println("Fin hilo");
                return;
            }

        }
    }
}
